"""
Django settings for portal_api project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import environ
from corsheaders.defaults import default_headers

env = environ.Env()
env_path = os.environ.get('CATVMS_API_ENV_PATH')
if env_path and os.path.exists(env_path):
    env.read_env(env.str('CATVMS_API_ENV_PATH', '.env'))

ENVIRONMENT = env.str('CATVMS_API_ENV_PATH', 'development')


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*b^y4z-ive9&&^zb*p4_ais$l2l08a(5^-40t&*lhyx54c=v^x'


ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'corsheaders',
    'rest_framework',
    'django_filters',
    'django_extensions',
    'api'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'portal_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(os.path.dirname(BASE_DIR), 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages'
            ],
        },
    },
]

WSGI_APPLICATION = 'portal_api.wsgi.application'


AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)

# Databases
DATABASES = {
    'default': env.db(),
    'readonly': env.db('DATABASE_READONLY_URL')
}

DATABASE_ROUTERS = ['portal_api.settings.DatabaseRouter.DatabaseRouter']
CACHE_BACKEND = 'django_redis.cache.RedisCache'
# Caches
CACHES = {
    'default': env.cache(),
    'token': {
        'BACKEND': CACHE_BACKEND,
        'LOCATION': env.str('REDIS_TOKEN_URL'),
    },
    'user_cache': {
        'BACKEND': CACHE_BACKEND,
        'LOCATION': env.str('REDIS_USER_CACHE'),
    },
    'api_icf_cache': {
        'BACKEND': CACHE_BACKEND,
        'LOCATION': env.str('API_ICF_CACHE'),
    },
    'local_cache': {
        'BACKEND': CACHE_BACKEND,
        'LOCATION': 'redis://127.0.0.1:6379/10'
    },
    'catv_data': {
        'BACKEND': CACHE_BACKEND,
        'LOCATION': env.str('API_CATV_CACHE_SERVER')
    },
}


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

LANGUAGES = [
    ('en', 'English'),
    ('ko', 'Korean'),
    ('ja', 'Japanese'),
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Rest framework settings

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'api.multitoken.tokens_auth.CachedTokenAuthentication'
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'catvPost': '15/min',
        'catvInternalPost': '1/min',
        'catvApiPost': '15/min'
    },
    'NUM_PROXIES': 2,
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
    'EXCEPTION_HANDLER': 'api.utils.custom_exception_handler',
    'DATETIME_FORMAT': '%s'
}


# cross origin setting
CORS_ALLOWED_ORIGIN_REGEXES = env.str('CORS_ORIGIN_WHITELIST_REGEX',
                                      default=[r'^https://.*?.*?\w+\.sentinelprotocol\.[a-zA-Z]+$',
                                               r'^http://localhost:[0-9]+$',
                                               r'^https://.*chainbounty\.io.*$'
                                               ]
                                      )
if not CORS_ALLOWED_ORIGIN_REGEXES:
    CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
)

CORS_ALLOW_HEADERS = default_headers + (
    "X-Authorization-Timestamp",
)


# Default auto-created primary keys

DEFAULT_AUTO_FIELD='django.db.models.AutoField'


# API Settings

EXPOSE_GENERAL_API = env.str('EXPOSE_GENERAL_API', True)
EXPOSE_FILE_API = env.str('EXPOSE_FILE_API', True)
EXPOSE_SEARCH_API = env.str('EXPOSE_SEARCH_API', False)
EXPOSE_INTERNAL_API = env.str('EXPOSE_INTERNAL_API', True)
EXPOSE_FREESEARCH_ENDPOINT = env.str('EXPOSE_FREESEARCH_ENDPOINT', True)


API_SETTINGS = {
    "VERSION": '1.0',
    "AUTO_COMPLETE_LIMIT": 10,
    "SEARCH_RESULT_LIMIT": 15,
    "ICO_BLACKLIST_LIMIT": 50,

    "S3_REGION": env.str('API_S3_REGION', os.environ.get("AWS_REGION", "ap-northeast-2")),
    "S3_BUCKET_NAME": env.str('API_S3_BUCKET_NAME', None),
    "S3_IMAGE_MEDIA_URL": env.str('API_S3_IMAGE_MEDIA_URL', None),
    "S3_ICO_IMAGE_KEY_PREFIX": env.str('API_S3_ICO_IMAGE_KEY_PREFIX', "ico_img/"),
    "S3_ICO_IMAGE_DEFAULT": env.str('API_S3_ICO_IMAGE_DEFAULT', 'https://portal.sentinelprotocol.io/img/ic_project_defult.png'),
    "S3_USER_IMAGE_KEY_PREFIX": env.str('API_S3_USER_IMAGE_KEY_PREFIX', "user_img/"),
    "S3_USER_IMAGE_DEFAULT": env.str('API_S3_USER_IMAGE_DEFAULT', 'https://portal.sentinelprotocol.io/img/anonymous.png'),

    "ATTACHED_FILE_S3_REGION": env.str('API_ATTACHED_FILE_S3_REGION', os.environ.get("AWS_REGION", "ap-northeast-2")),
    "ATTACHED_FILE_S3_BUCKET_NAME": env.str('API_ATTACHED_FILE_S3_BUCKET_NAME', None),
    "ATTACHED_FILE_S3_KEY_PREFIX": env.str('API_ATTACHED_FILE_S3_KEY_PREFIX', 'files/'),
    "ATTACHED_FILE_MEDIA_URL": env.str('API_ATTACHED_FILE_MEDIA_URL', None),
    'ATTACHED_FILE_MIN_SIZE': env.int('API_ATTACHED_FILE_MIN_SIZE', 50),
    'ATTACHED_FILE_NAME_MAX_LEN': env.int('API_ATTACHED_FILE_NAME_MAX_LEN', 255),
    'ATTACHED_FILE_UPLOAD_NUM_LIMIT': env.int('API_ATTACHED_FILE_UPLOAD_NUM_LIMIT', 1),
    'ATTACHED_FILE_ALLOWED_TYPES': env.str('API_ATTACHED_FILE_ALLOWED_TYPES',
                                           'txt|pdf|mp4|png|jpg|jpeg|bmp|gif|csv'),

    "ICO_LIST_DETAIL_LEN": env.int('API_ICO_LIST_DETAIL_LEN', 300),
    "CASE_LIST_DETAIL_LEN": env.int('API_CASE_LIST_DETAIL_LEN', 300),
    "CASE_TITLE_MAX_LEN": env.int('API_CASE_TITLE_MAX_LEN', 128),
    "CASE_DETAIL_MAX_LEN": env.int('API_CASE_DETAIL_MAX_LEN', 4096),
    "CASE_REPORTER_MAX_LEN": env.int('API_CASE_REPORTER_MAX_LEN', 128),
    "CASE_SECURITY_TAGS_LIMIT": env.int('API_CASE_SECURITY_TAGS_LIMIT', 5),
    "CASE_ATTACHED_FILE_MAX_LIMIT": env.int('API_CASE_ATTACHED_FILE_MAX_LIMIT', 20),
    "INDICATOR_LIST_DETAIL_LEN": env.int('API_INDICATOR_LIST_DETAIL_LEN', 300),
    "INDICATOR_DETAIL_MAX_LEN": env.int('API_INDICATOR_DETAIL_MAX_LEN', 4096),
    "INDICATOR_PATTERN_MAX_LEN": env.int('API_INDICATOR_PATTERN_MAX_LEN', 256),
    "COMMENT_BODY_MAX_LEN": env.int('API_COMMENT_BODY_MAX_LEN', 1024),
    "TRDB_API_URL": env.str('API_TRDB_API_URL', 'http://localhost:3001/v1/'),
    "UPPWARD_CACHE_SERVER": env.str("API_UPPWARD_CACHE_SERVER", None),

    'TOKEN_REDIS_DB_NAME': env.str('API_TOKEN_REDIS_DB_NAME', 'token'),
    'TOKEN_RESET_TTL_ON_USER_LOG_IN': True,
    'TOKEN_OVERWRITE_NONE_TTL': True,
    'TOKEN_EXPIRE_TIME': env.int('API_TOKEN_EXPIRE_TIME', 7200),
    'TOKEN_ENCRYPT_PRIVATE_KEY': env.str('API_TOKEN_ENCRYPT_PRIVATE_KEY', None),
    'DECRYPT_TIMESTAMP_LEEWAY': env.int('API_DECRYPT_TIMESTAMP_LEEWAY', 15 * 60),
    'CELERY_BROKER_URL': env.str('API_CELERY_BROKER_URL', None),
    'CELERY_RESULT_BACKEND': env.str('API_CELERY_RESULT_BACKEND', None),
    'EMAIL_HOST_USER': env.str('API_EMAIL_HOST_USER', None),
    'EMAIL_HOST_PASSWORD': env.str('API_EMAIL_HOST_PASSWORD', None),
    'WEB_URL': env.str('API_WEB_URL', ''),
    "PORTAL_API_MODE": env.str("PORTAL_API_MODE", ''),
    "KAFKA_BROKER_1": env.str("KAFKA_BROKER_1", None),
    "KAFKA_BROKER_2": env.str("KAFKA_BROKER_2", None),
    "KAFKA_BROKER_3": env.str("KAFKA_BROKER_3", None),
    "ADMIN_WALLET_ADDRESS": env.str('ADMIN_WALLET_ADDRESS', None),
    "ADMIN_WALLET_KEY": env.str('ADMIN_WALLET_KEY', None),
    "CONTRACT_ADDRESS": env.str('CONTRACT_ADDRESS', None),
    "CONTRACT_ABI": env.str('CONTRACT_ABI', None),
    "TOKEN_ADDRESS": env.str('TOKEN_ADDRESS', None),
    "TOKEN_ABI": env.str('TOKEN_ABI', None),
    "TRDB_HOST": env.str('TRDB_HOST', None),
    "TRDB_USERNAME": env.str('TRDB_USERNAME', None),
    "TRDB_PASSWORD": env.str('TRDB_PASSWORD', None),
    "TRDB_PORT": env.int('TRDB_PORT', 5432),
    "TRDB_DBNAME": env.str('TRDB_DBNAME', 'portal'),
    "TRDB_SSL_MODE": env.str('TRDB_SSL_MODE', 'prefer'),
    "LOCAL_HOST": env.str('LOCAL_HOST', None),
    "LOCAL_DBNAME": env.str('LOCAL_DBNAME', None),
    "LOCAL_USERNAME": env.str('LOCAL_USERNAME', None),
    "LOCAL_PASSWORD": env.str('LOCAL_PASSWORD', None),
    "LOCAL_PORT": env.int('LOCAL_PORT', 5432),
    "LOCAL_SSL_MODE": env.str('LOCAL_SSL_MODE', 'prefer'),
    "TIME_INTERVAL": env.int('TIME_INTERVAL', 24),
    "SWITCH_ES_SEARCH": env.bool('API_SWITCH_ES_SEARCH', True),
    "BASE_API_URL": env.str('API_BASE_URL', 'http://localhost:8000/'),
    "LYZE_API_KEY": env.str('API_LYZE_KEY'),
    "KAFKA_CATV_TOPIC": env.str("API_KAFKA_CATV_TOPIC", "catv-requests"),
    "SWITCH_CATV_KAFKA": env.bool("API_SWITCH_CATV_KAFKA", True),
    "CATV_TX_LIMIT": env.int("API_CATV_TX_LIMIT", 50000),
    "CATV_ADDRESS_LIMT": env.int("API_CATV_ADDRESS_LIMIT", 50000),
    "CATV_MAX_SCALED_NODES": env.int("API_CATV_MAX_SCALED_NODES", 500),
    "CATV_GRAPH_NODES_CUTOFF": env.int("API_CATV_GRAPH_NODES_CUTOFF", 1000),
    "CATV_NUM_JOBS_PICK": env.int("API_CATV_NUM_JOBS_PICK", 3),
    "SEARCH_BACKEND_URL": env.str("API_SEARCH_BACKEND_URL", "http://localhost:8000/"),
    "VERIFY_TX_AMT": env.str("API_VERIFY_TX_AMT", "0.000118"),
    "MAB_USER_UPGRADE": env.int("API_MAB_USER_UPGRADE", 10000),
    "RABBIT_MQ_URL": env.str("RABBIT_MQ_URL", 'localhost:5672'),
    "RABBIT_MQ_PORT": env.str("RABBIT_MQ_PORT", 5671),
    "RABBIT_MQ_HOST":env.str("RABBIT_MQ_HOST", "localhost"),
    "RABBIT_MQ_USERNAME": env.str("RABBIT_MQ_USERNAME", 'guest'),
    "RABBIT_MQ_PASSWORD": env.str("RABBIT_MQ_PASSWORD", 'guest'),
    "RABBIT_MQ_REGION": env.str("RABBIT_MQ_REGION", 'ap-southeast-1'),
    "RABBIT_MQ_BROKER_ID":env.str("RABBIT_MQ_BROKER_ID", 'b-8d90beb2-5764-4bf6-bff6-c480c228568c'),
    "RABBIT_MQ_ENV":env.str("RABBIT_MQ_ENV", "production"),
    "RABBIT_MQ_LOCAL_URL":env.str("RABBIT_MQ_LOCAL_URL", "rabbitmq"),
    "API_USER_CACHE": env.str('API_USER_CACHE_DB', 'user_cache'),
    "API_ICF_CACHE": env.str('API_ICF_CACHE_DB', 'api_icf_cache'),
    "GRAPHQL_ENDPOINT": env.str('API_GRAPHQL_ENDPOINT', 'https://graphql.bitquery.io'),
    "GRAPHQL_ENDPOINT_V2": env.str('API_GRAPHQL_ENDPOINT_V2', 'https://streaming.bitquery.io/graphql'),
    "GRAPHQL_X_API_KEY": env.str('GRAPHQL_API_KEY', ''),
    "API_ELASTICSEARCH_HOST": env.str('API_ELASTICSEARCH_HOST', ''),
    "BLOXY_API_KEY" : env.str('API_BLOXY_KEY', 'ACCG4wmxpYKkd'),
    "ES_INDEX": env.str('ES_INDEX', 'dev_latest_indicator'),
    "API_ELASTICSEARCH_CREDENTIALS": env.str('API_ELASTICSEARCH_CREDENTIALS', ''),
    "ES_FLAG": env.bool('ES_FLAG', True),
    "CATV_REPORT_BASE_URL": env.str('CATV_REPORT_BASE_URL', "https://stgportal.sentinelprotocol.io/catv-report"),
    "CATV_NEO_REPORT_BASE_URL": env.str('CATV_NEO_REPORT_BASE_URL', "https://stgcatv.sentinelprotocol.io/catv-report"),
    "TRACER_ENDPOINT": env.str("TRACER_ENDPOINT", "https://stgtracer-api.sentinelprotocol.io/"),
}

# Add AWS Private IP to ALLOWED_HOSTS.
ALLOWED_HOSTS += env.str("ECS_PRIVATE_IP", "").split(",") if len(env.str("ECS_PRIVATE_IP", '')) > 0 else []

# celery
CELERY_BROKER_URL = API_SETTINGS['CELERY_BROKER_URL']
CELERY_RESULT_BACKEND = API_SETTINGS['CELERY_RESULT_BACKEND']
CELERYD_CONCURRENCY = 2
CELERY_IMPORTS = ('api.tasks',)


# BLOXY API
BLOXY_DIST_ENDPOINT = env.str(
    'API_BLOXY_DIST_ENDPOINT', 'https://sentinel.api.bitquery.io/coinpath/outbound_graph')
BLOXY_SRC_ENDPOINT = env.str(
    'API_BLOXY_SRC_ENDPOINT', 'https://sentinel.api.bitquery.io/coinpath/inbound_graph')
BLOXY_BTC_SRC_ENDPOINT = env.str(
    'API_BLOXY_BTC_SRC_ENDPOINT', 'https://ctds.api.bitquery.io/bitcoin:coinpath/inbound_graph')
BLOXY_LTC_SRC_ENDPOINT = env.str(
    'API_BLOXY_LTC_SRC_ENDPOINT', 'https://sentinel.api.bitquery.io/bitcoin:coinpath/inbound_graph')
BLOXY_BTC_DIST_ENDPOINT = env.str(
    'API_BLOXY_BTC_DIST_ENDPOINT', 'https://ctds.api.bitquery.io/bitcoin:coinpath/outbound_graph')
BLOXY_LTC_DIST_ENDPOINT = env.str(
    'API_BLOXY_LTC_DIST_ENDPOINT', 'https://sentinel.api.bitquery.io/bitcoin:coinpath/outbound_graph')
BLOXY_ETHCOINPATH_ENDPOINT = env.str(
    'API_BLOXY_ETHCOINPATH_ENDPOINT', 'https://sentinel.api.bitquery.io/coinpath/paths')
BLOXY_BTCCOINPATH_ENDPOINT = env.str(
    'API_BLOXY_BTCCOINPATH_ENDPOINT', 'https://sentinel.api.bitquery.io/bitcoin:coinpath/paths')
BLOXY_ETH_DIST_ENDPOINT = env.str(
    'API_BLOXY_ETH_DIST_ENDPOINT', 'https://ctds.api.bitquery.io/sentinel/outbound_graph_with_stat')
BLOXY_KLAY_DIST_ENDPOINT = env.str(
    'API_BLOXY_KLAY_DIST_ENDPOINT', 'https://sentinel.api.bitquery.io/sentinel/outbound_graph_with_stat')
BLOXY_ETH_SRC_ENDPOINT = env.str(
    'API_BLOXY_ETH_SRC_ENDPOINT', 'https://ctds.api.bitquery.io/sentinel/inbound_graph_with_stat')
BLOXY_KLAY_SRC_ENDPOINT = env.str(
    'API_BLOXY_KLAY_SRC_ENDPOINT', 'https://sentinel.api.bitquery.io/sentinel/inbound_graph_with_stat')

LYZE_API_KEY = env.str('API_LYZE_KEY')
LYZE_DIST_ENDPOINT = env.str('API_LYZE_DIST_ENDPOINT', 'https://upp.lyze.ai/btc_forward_tracking')
LYZE_SRC_ENDPOINT = env.str('API_LYZE_SRC_ENDPOINT', 'https://upp.lyze.ai/btc_backward_tracking')
LYZE_TXLIST_ENDPOINT = env.str('API_LYZE_TXLIST_ENDPOINT', 'https://upp.lyze.ai/btc_address_transfers')

#RABBIT MQ
RABBIT_MQ_URL = API_SETTINGS['RABBIT_MQ_URL']
RABBIT_MQ_USERNAME = API_SETTINGS['RABBIT_MQ_USERNAME']
RABBIT_MQ_PASSWORD = API_SETTINGS['RABBIT_MQ_PASSWORD']
RABBIT_MQ_PORT = API_SETTINGS['RABBIT_MQ_PORT']
RABBIT_MQ_REGION=API_SETTINGS['RABBIT_MQ_REGION']
RABBIT_MQ_BROKER_ID=API_SETTINGS['RABBIT_MQ_BROKER_ID']
RABBIT_MQ_ENV=API_SETTINGS['RABBIT_MQ_ENV']
RABBIT_MQ_LOCAL_URL=API_SETTINGS['RABBIT_MQ_LOCAL_URL']


# TRACER
TRACER_ENDPOINT = API_SETTINGS["TRACER_ENDPOINT"]