"""
Django settings for portal_api project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import environ
import djcelery
from corsheaders.defaults import default_headers
from datetime import timedelta

env = environ.Env()
env_path = os.environ.get('PORTAL_API_ENV_PATH')
if env_path and os.path.exists(env_path):
    env.read_env(env.str('PORTAL_API_ENV_PATH', '.env'))

ENVIRONMENT = env.str('PORTAL_API_ENV', 'development')


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*b^y4z-ive9&&^zb*p4_ais$l2l08a(5^-40t&*lhyx54c=v^x'


ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'djcelery',
    'corsheaders',
    'rest_framework',
    'django_filters',
    'django_extensions',
    'social_django',
    'api'
]

MIDDLEWARE = [
    'django.middleware.gzip.GZipMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'portal_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(os.path.dirname(BASE_DIR), 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'portal_api.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        'OPTIONS': {
            'user_attributes': ('nickname', 'email')
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (
    'social_core.backends.open_id.OpenIdAuth',
    'social_core.backends.google.GoogleOpenId',
    'social_core.backends.google.GoogleOAuth',
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

# Databases
DATABASES = {
    'default': env.db(),
    'readonly': env.db('DATABASE_READONLY_URL')
}

DATABASE_ROUTERS = ['portal_api.settings.DatabaseRouter.DatabaseRouter']

# Caches
CACHES = {
    'default': env.cache(),
    'token': env.cache('REDIS_TOKEN_URL'),
    'uppward': {
        'BACKEND': 'redis_cache.RedisCache',
        'LOCATION': env.str('API_UPPWARD_CACHE_SERVER'),
        "OPTIONS": {
            "SOCKET_CONNECT_TIMEOUT": 3,
            "SOCKET_TIMEOUT": 3,
        }
    },
    'local_cache': {
        'BACKEND': 'redis_cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/10'
    },
    'catv_data': {
        'BACKEND': 'redis_cache.RedisCache',
        'LOCATION': env.str('API_CATV_CACHE_SERVER')
    }
}


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

LANGUAGES = [
    ('en', 'English'),
    ('ko', 'Korean'),
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Rest framework settings

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'api.multitoken.tokens_auth.CachedTokenAuthentication'
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'userLogin': '5/min',
        'changePassword': '5/min',
        'fileUpload': '20/min',
        'casePost': '5/min',
        "signup": "5/min",
        'emailVerification': '5/min',
        'indicatorPost': '20/min',
        'caraPost': '3/min',
        'catvPost': '5/min',
        'guestSearchGet': '20/min',
        'catvInternalPost': '1/min',
        'upgradePostPut': '5/hour'
    },
    'NUM_PROXIES': 2,
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
    'EXCEPTION_HANDLER': 'api.utils.custom_exception_handler',
    'DATETIME_FORMAT': '%s'
}


# cross origin setting

CORS_ORIGIN_WHITELIST = env.str('CORS_ORIGIN_WHITELIST', default="").split(",")
if not CORS_ORIGIN_WHITELIST:
    CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
)

CORS_ALLOW_HEADERS = default_headers + (
    "X-Authorization-Timestamp",
)


# file stoage

DEFAULT_FILE_STORAGE = "api.storages.s3.S3Storage"

# Python Social Auth (PSA) settings
SOCIAL_AUTH_POSTGRES_JSONFIELD = True
SOCIAL_AUTH_USERNAME_IS_FULL_EMAIL = True
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = env.str('API_SOCIAL_AUTH_GOOGLE_OAUTH2_KEY', '')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = env.str('API_SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET', '')
SOCIAL_AUTH_USER_MODEL = 'api.User'
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = ['email', 'profile']
SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'api.social_pipelines.get_username',
    'social_core.pipeline.social_auth.associate_by_email',
    'api.social_pipelines.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
)


# API Settings

EXPOSE_GENERAL_API = env.str('EXPOSE_GENERAL_API', True)
EXPOSE_FILE_API = env.str('EXPOSE_FILE_API', True)
EXPOSE_SEARCH_API = env.str('EXPOSE_SEARCH_API', False)
EXPOSE_INTERNAL_API = env.str('EXPOSE_INTERNAL_API', True)
EXPOSE_FREESEARCH_ENDPOINT = env.str('EXPOSE_FREESEARCH_ENDPOINT', True)


API_SETTINGS = {
    "VERSION": '1.0',
    "AUTO_COMPLETE_LIMIT": 10,
    "SEARCH_RESULT_LIMIT": 15,
    "ICO_BLACKLIST_LIMIT": 50,

    "S3_REGION": env.str('API_S3_REGION', os.environ.get("AWS_REGION", "ap-northeast-2")),
    "S3_BUCKET_NAME": env.str('API_S3_BUCKET_NAME', None),
    "S3_IMAGE_MEDIA_URL": env.str('API_S3_IMAGE_MEDIA_URL', None),
    "S3_ICO_IMAGE_KEY_PREFIX": env.str('API_S3_ICO_IMAGE_KEY_PREFIX', "ico_img/"),
    "S3_ICO_IMAGE_DEFAULT": env.str('API_S3_ICO_IMAGE_DEFAULT', 'https://portal.sentinelprotocol.io/img/ic_project_defult.png'),
    "S3_USER_IMAGE_KEY_PREFIX": env.str('API_S3_USER_IMAGE_KEY_PREFIX', "user_img/"),
    "S3_USER_IMAGE_DEFAULT": env.str('API_S3_USER_IMAGE_DEFAULT', 'https://portal.sentinelprotocol.io/img/anonymous.png'),

    "ATTACHED_FILE_S3_REGION": env.str('API_ATTACHED_FILE_S3_REGION', os.environ.get("AWS_REGION", "ap-northeast-2")),
    "ATTACHED_FILE_S3_BUCKET_NAME": env.str('API_ATTACHED_FILE_S3_BUCKET_NAME', None),
    "ATTACHED_FILE_S3_KEY_PREFIX": env.str('API_ATTACHED_FILE_S3_KEY_PREFIX', 'files/'),
    "ATTACHED_FILE_MEDIA_URL": env.str('API_ATTACHED_FILE_MEDIA_URL', None),
    'ATTACHED_FILE_MIN_SIZE': env.int('API_ATTACHED_FILE_MIN_SIZE', 50),
    'ATTACHED_FILE_NAME_MAX_LEN': env.int('API_ATTACHED_FILE_NAME_MAX_LEN', 255),
    'ATTACHED_FILE_UPLOAD_NUM_LIMIT': env.int('API_ATTACHED_FILE_UPLOAD_NUM_LIMIT', 1),
    'ATTACHED_FILE_ALLOWED_TYPES': env.str('API_ATTACHED_FILE_ALLOWED_TYPES',
                                           'txt|pdf|mp4|png|jpg|jpeg|bmp|gif|csv'),

    "ICO_LIST_DETAIL_LEN": env.int('API_ICO_LIST_DETAIL_LEN', 300),
    "CASE_LIST_DETAIL_LEN": env.int('API_CASE_LIST_DETAIL_LEN', 300),
    "CASE_TITLE_MAX_LEN": env.int('API_CASE_TITLE_MAX_LEN', 128),
    "CASE_DETAIL_MAX_LEN": env.int('API_CASE_DETAIL_MAX_LEN', 4096),
    "CASE_REPORTER_MAX_LEN": env.int('API_CASE_REPORTER_MAX_LEN', 128),
    "CASE_SECURITY_TAGS_LIMIT": env.int('API_CASE_SECURITY_TAGS_LIMIT', 5),
    "CASE_ATTACHED_FILE_MAX_LIMIT": env.int('API_CASE_ATTACHED_FILE_MAX_LIMIT', 20),
    "INDICATOR_LIST_DETAIL_LEN": env.int('API_INDICATOR_LIST_DETAIL_LEN', 300),
    "INDICATOR_DETAIL_MAX_LEN": env.int('API_INDICATOR_DETAIL_MAX_LEN', 4096),
    "INDICATOR_PATTERN_MAX_LEN": env.int('API_INDICATOR_PATTERN_MAX_LEN', 256),
    "COMMENT_BODY_MAX_LEN": env.int('API_COMMENT_BODY_MAX_LEN', 1024),
    "TRDB_API_URL": env.str('API_TRDB_API_URL', 'http://localhost:3001/v1/'),
    "UPPWARD_CACHE_SERVER": env.str("API_UPPWARD_CACHE_SERVER", None),

    'TOKEN_REDIS_DB_NAME': env.str('API_TOKEN_REDIS_DB_NAME', 'token'),
    'TOKEN_RESET_TTL_ON_USER_LOG_IN': True,
    'TOKEN_OVERWRITE_NONE_TTL': True,
    'TOKEN_EXPIRE_TIME': env.int('API_TOKEN_EXPIRE_TIME', 7200),
    'TOKEN_ENCRYPT_PRIVATE_KEY': env.str('API_TOKEN_ENCRYPT_PRIVATE_KEY', None),
    'DECRYPT_TIMESTAMP_LEEWAY': env.int('API_DECRYPT_TIMESTAMP_LEEWAY', 15 * 60),
    'CELERY_BROKER_URL': env.str('API_CELERY_BROKER_URL', None),
    'CELERY_RESULT_BACKEND': env.str('API_CELERY_RESULT_BACKEND', None),
    'EMAIL_HOST_USER': env.str('API_EMAIL_HOST_USER', None),
    'EMAIL_HOST_PASSWORD': env.str('API_EMAIL_HOST_PASSWORD', None),
    'WEB_URL': env.str('API_WEB_URL', ''),
    "PORTAL_API_MODE": env.str("PORTAL_API_MODE", ''),
    "KAFKA_BROKER_1": env.str("KAFKA_BROKER_1", None),
    "KAFKA_BROKER_2": env.str("KAFKA_BROKER_2", None),
    "KAFKA_BROKER_3": env.str("KAFKA_BROKER_3", None),
    "ADMIN_WALLET_ADDRESS": env.str('ADMIN_WALLET_ADDRESS', None),
    "ADMIN_WALLET_KEY": env.str('ADMIN_WALLET_KEY', None),
    "CONTRACT_ADDRESS": env.str('CONTRACT_ADDRESS', None),
    "CONTRACT_ABI": env.str('CONTRACT_ABI', None),
    "REWARDS_URL": env.str('REWARDS_URL', None),
    "TOKEN_ADDRESS": env.str('TOKEN_ADDRESS', None),
    "TOKEN_ABI": env.str('TOKEN_ABI', None),
    "TRDB_HOST": env.str('TRDB_HOST', None),
    "TRDB_USERNAME": env.str('TRDB_USERNAME', None),
    "TRDB_PASSWORD": env.str('TRDB_PASSWORD', None),
    "TRDB_PORT": env.int('TRDB_PORT', 5432),
    "TRDB_DBNAME": env.str('TRDB_DBNAME', 'portal'),
    "TRDB_SSL_MODE": env.str('TRDB_SSL_MODE', 'prefer'),
    "LOCAL_HOST": env.str('LOCAL_HOST', None),
    "LOCAL_DBNAME": env.str('LOCAL_DBNAME', None),
    "LOCAL_USERNAME": env.str('LOCAL_USERNAME', None),
    "LOCAL_PASSWORD": env.str('LOCAL_PASSWORD', None),
    "LOCAL_PORT": env.int('LOCAL_PORT', 5432),
    "LOCAL_SSL_MODE": env.str('LOCAL_SSL_MODE', 'prefer'),
    "TIME_INTERVAL": env.int('TIME_INTERVAL', 24),
    "KAFKA_USER_TOPIC": env.str('KAFKA_USER_TOPIC', 'cara-address'),
    "KAFKA_BATCH_TOPIC": env.str('KAFKA_BATCH_TOPIC', 'cara-indicator'),
    "KAFKA_CONSUMER_TOPIC": env.str('KAFKA_CONSUMER_TOPIC', 'cara-address-results-test'),
    "SWITCH_ES_SEARCH": env.bool('API_SWITCH_ES_SEARCH', True),
    "BASE_API_URL": env.str('API_BASE_URL', 'http://localhost:8000/'),
    "LYZE_API_KEY": env.str('API_LYZE_KEY'),
    "KAFKA_CRAWLED_CASE_TOPIC": env.str("API_KAFKA_CRAWLED_CASE_TOPIC", "crawled-cases"),
    "KAFKA_PORTAL_CASE_TOPIC": env.str("API_KAFKA_PORTAL_CASE_TOPIC", "portal-cases"),
    "KAFKA_DELAYED_CASE_TOPIC": env.str("API_KAFKA_DELAYED_CASE_TOPIC", "crawled-delayed-cases"),
    "KAFKA_CATV_TOPIC": env.str("API_KAFKA_CATV_TOPIC", "catv-requests"),
    "SWITCH_CATV_KAFKA": env.bool("API_SWITCH_CATV_KAFKA", True),
    "CATV_TX_LIMIT": env.int("API_CATV_TX_LIMIT", 50000),
    "CATV_ADDRESS_LIMT": env.int("API_CATV_ADDRESS_LIMIT", 50000),
    "CATV_MAX_SCALED_NODES": env.int("API_CATV_MAX_SCALED_NODES", 500),
    "CATV_GRAPH_NODES_CUTOFF": env.int("API_CATV_GRAPH_NODES_CUTOFF", 1000),
    "CATV_NUM_JOBS_PICK": env.int("API_CATV_NUM_JOBS_PICK", 3),
    "SEARCH_BACKEND_URL": env.str("API_SEARCH_BACKEND_URL", "http://localhost:8000/"),
    "MAINNET_URL": env.str("API_MAINNET_URL", "https://mainnet.infura.io/v3/acc7e98bea464efa91f383ce2dd3d764"),
    "VERIFY_TX_AMT": env.str("API_VERIFY_TX_AMT", "0.000118"),
    "MAB_USER_UPGRADE": env.int("API_MAB_USER_UPGRADE", 10000),
}

# Add AWS Private IP to ALLOWED_HOSTS.
ALLOWED_HOSTS += env.str("ECS_PRIVATE_IP", "").split(",") if len(env.str("ECS_PRIVATE_IP", '')) > 0 else []

# celery
djcelery.setup_loader()
BROKER_URL = API_SETTINGS['CELERY_BROKER_URL']
CELERY_RESULT_BACKEND = API_SETTINGS['CELERY_BROKER_URL']
CELERYD_CONCURRENCY = 2
CELERY_IMPORTS = ('api.tasks',)
CELERYBEAT_SCHEDULE = {
    'check-invites-every-45-minutes': {
        'task': 'api.tasks.CheckDeleteInvitesTask',
        'schedule': timedelta(minutes=45),
    },
    'check-user-upgrade-every-hour': {
        'task': 'api.tasks.CheckUserUpgradeTask',
        'schedule': timedelta(minutes=60),
    },
    'check-quota-every-year': {
        'task': 'api.tasks.RefillCreditsYearlyTask',
        'schedule': timedelta(minutes=30),
    }
}
# email
EMAIL_BACK_END = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'email-smtp.us-east-1.amazonaws.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = API_SETTINGS['EMAIL_HOST_USER']
EMAIL_HOST_PASSWORD = API_SETTINGS['EMAIL_HOST_PASSWORD']

# BLOXY API
BLOXY_API_KEY = env.str('API_BLOXY_KEY')

BLOXY_DIST_ENDPOINT = env.str('API_BLOXY_DIST_ENDPOINT', 'https://sentinel.api.bitquery.io/coinpath/outbound_graph')
BLOXY_SRC_ENDPOINT = env.str('API_BLOXY_SRC_ENDPOINT', 'https://sentinel.api.bitquery.io/coinpath/inbound_graph')
BLOXY_BTC_SRC_ENDPOINT = env.str('API_BLOXY_BTC_SRC_ENDPOINT', 'https://sentinel.api.bitquery.io/bitcoin:coinpath/inbound_graph')
BLOXY_BTC_DIST_ENDPOINT = env.str('API_BLOXY_BTC_DIST_ENDPOINT', 'https://sentinel.api.bitquery.io/bitcoin:coinpath/outbound_graph')
BLOXY_ETHCOINPATH_ENDPOINT = env.str('API_BLOXY_ETHCOINPATH_ENDPOINT', 'https://sentinel.api.bitquery.io/coinpath/paths')
BLOXY_BTCCOINPATH_ENDPOINT = env.str('API_BLOXY_BTCCOINPATH_ENDPOINT', 'https://sentinel.api.bitquery.io/bitcoin:coinpath/paths')
BLOXY_ETH_DIST_ENDPOINT = env.str('API_BLOXY_ETH_DIST_ENDPOINT', 'https://sentinel.api.bitquery.io/sentinel/outbound_graph_with_stat')
BLOXY_ETH_SRC_ENDPOINT = env.str('API_BLOXY_ETH_SRC_ENDPOINT', 'https://sentinel.api.bitquery.io/sentinel/inbound_graph_with_stat')

LYZE_API_KEY = env.str('API_LYZE_KEY')
LYZE_DIST_ENDPOINT = env.str('API_LYZE_DIST_ENDPOINT', 'https://upp.lyze.ai/btc_forward_tracking')
LYZE_SRC_ENDPOINT = env.str('API_LYZE_SRC_ENDPOINT', 'https://upp.lyze.ai/btc_backward_tracking')
LYZE_TXLIST_ENDPOINT = env.str('API_LYZE_TXLIST_ENDPOINT', 'https://upp.lyze.ai/btc_address_transfers')

#CARA KAFKA
KAFKA_BROKER_1 = API_SETTINGS['KAFKA_BROKER_1']
KAFKA_BROKER_2 = API_SETTINGS['KAFKA_BROKER_2']
KAFKA_BROKER_3 = API_SETTINGS['KAFKA_BROKER_3']
KAFKA_USER_TOPIC = API_SETTINGS['KAFKA_USER_TOPIC']
KAFKA_BATCH_TOPIC = API_SETTINGS['KAFKA_BATCH_TOPIC']
KAFKA_CONSUMER_TOPIC = API_SETTINGS['KAFKA_CONSUMER_TOPIC']

#CARA LISTENER
TRDB_HOST = API_SETTINGS['TRDB_HOST']
TRDB_USERNAME = API_SETTINGS['TRDB_USERNAME']
TRDB_PASSWORD = API_SETTINGS['TRDB_PASSWORD']
TRDB_PORT = API_SETTINGS['TRDB_PORT']
TRDB_DBNAME = API_SETTINGS['TRDB_DBNAME']
TRDB_SSL_MODE = API_SETTINGS['TRDB_SSL_MODE']
LOCAL_HOST = API_SETTINGS['LOCAL_HOST']
LOCAL_DBNAME = API_SETTINGS['LOCAL_DBNAME']
LOCAL_USERNAME = API_SETTINGS['LOCAL_USERNAME']
LOCAL_PASSWORD = API_SETTINGS['LOCAL_PASSWORD']
LOCAL_PORT = API_SETTINGS['LOCAL_PORT']
LOCAL_SSL_MODE = API_SETTINGS['LOCAL_SSL_MODE']
TIME_INTERVAL = API_SETTINGS['TIME_INTERVAL']

#REWARDS ADMIN
ADMIN_WALLET_ADDRESS = API_SETTINGS['ADMIN_WALLET_ADDRESS']
ADMIN_WALLET_KEY = API_SETTINGS['ADMIN_WALLET_KEY']
CONTRACT_ADDRESS = API_SETTINGS['CONTRACT_ADDRESS']
CONTRACT_ABI = API_SETTINGS['CONTRACT_ABI']
REWARDS_URL = API_SETTINGS['REWARDS_URL']
TOKEN_ADDRESS = API_SETTINGS['TOKEN_ADDRESS']
TOKEN_ABI = API_SETTINGS['TOKEN_ABI']
