version: 0.2
env:
  variables:
    NODE_VERSION: '8.11.0'
    IMAGE_VERSION: 'v1.1.0'

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - git clone https://uppindicator:$INDICATOR_TOKEN@github.com/upphub/indicator-lib.git library/indicator-lib
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - MANIFEST=$(aws ecr batch-get-image --repository-name $IMAGE_REPO_NAME --image-ids imageTag=latest --query images[].imageManifest --output text)
      - DATE_TAG=$(date +%Y%m%d-%H%M%S)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build . --build-arg SLACK_URL=$SLACK_URL --build-arg PM2_CONFIG_FILE=$PM2_CONFIG_FILE --build-arg EXPOSE_GENERAL_API=$EXPOSE_GENERAL_API --build-arg EXPOSE_FILE_API=$EXPOSE_FILE_API --build-arg PORTAL_API_VERSION=$IMAGE_VERSION -t $IMAGE_REPO_NAME:latest
      - docker tag $IMAGE_REPO_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - docker tag $IMAGE_REPO_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_VERSION
      - docker tag $IMAGE_REPO_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$DATE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_VERSION
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$DATE_TAG

      - echo "[{\"name\":\"UPP-STG-$SERVICE_NAME\",\"imageUri\":\"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$DATE_TAG\"}]" > stg-definitions.json
      - echo "[{\"name\":\"UPP-PRD-$SERVICE_NAME\",\"imageUri\":\"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$DATE_TAG\"}]" > prd-definitions.json
      - aws ecr put-image --repository-name $IMAGE_REPO_NAME --image-tag rollback --image-manifest "$MANIFEST"
artifacts:
  files:
    - stg-definitions.json
    - prd-definitions.json
    - stg-definitions-f.json
    - prd-definitions-f.json

