FROM python:3.6.5-stretch

MAINTAINER jmye <jmye@uppsala.foundation>

ARG PM2_CONFIG_FILE=pm2_admin.json
ARG EXPOSE_GENERAL_API=true
ARG EXPOSE_FILE_API=true
ARG SLACK_URL
ARG ALLOWED_HOSTS
ARG CORS_ORIGIN_WHITELIST
ARG PORTAL_API_ENV=development
ARG CONTAINER_TYPE=portal_admin

ENV EXPOSE_GENERAL_API=$EXPOSE_GENERAL_API
ENV EXPOSE_FILE_API=$EXPOSE_FILE_API
ENV ALLOWED_HOSTS=$ALLOWED_HOSTS
ENV CORS_ORIGIN_WHITELIST=$CORS_ORIGIN_WHITELIST
ENV PORTAL_API_ENV=$PORTAL_API_ENV
ENV PORTAL_PM2_CONFIG_FILE=$PM2_CONFIG_FILE
ENV STATIC_ROOT=/app/static
ENV CONTAINER_TYPE=$CONTAINER_TYPE

WORKDIR /app

# Install packages
RUN apt-get update

# Install nodejs and pm2
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get update && \
    apt-get install -y nodejs redis-server && \
    npm install pm2 -g

# Install requirements
COPY ./requirements/${PORTAL_API_ENV}.txt ./requirements.txt
COPY ./library ./library
RUN pip install -r ./requirements.txt
RUN pip install uwsgi
RUN pip install -e ./library/indicator-lib/src/py

# Add uppsala user.
RUN groupadd -g 999 uppsala && \
    useradd -r -u 999 -g uppsala uppsala
WORKDIR /app
RUN chown uppsala:uppsala /app
RUN usermod -d /app uppsala
USER uppsala

# Install pm2-slack
RUN pm2 install pm2-slack
RUN pm2 set pm2-slack:slack_url ${SLACK_URL}
RUN pm2 set pm2-slack:log false
RUN pm2 set pm2-slack:error false
RUN pm2 set pm2-slack:kill true
RUN pm2 set pm2-slack:exception false
RUN pm2 set pm2-slack:restart false
RUN pm2 set pm2-slack:delete true
RUN pm2 set pm2-slack:stop true
RUN pm2 set pm2-slack:'restart overlimit' true
RUN pm2 set pm2-slack:buffer_seconds 5

# Bundle APP files
COPY . .
COPY ./deploy ./deploy

# RUN
CMD pm2-runtime start /app/deploy/conf/$PORTAL_PM2_CONFIG_FILE --web
