# Generated by Django 2.0.6 on 2021-10-11 11:29

import api.models
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import enumfields.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloxyDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('depth_limit', models.IntegerField(null=True)),
                ('transaction_limit', models.IntegerField(null=True)),
                ('from_time', models.DateTimeField(null=True)),
                ('till_time', models.DateTimeField(null=True)),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('token_address', models.CharField(max_length=50, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'api_bloxy_distribution',
            },
        ),
        migrations.CreateModel(
            name='BloxySource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('depth_limit', models.IntegerField(null=True)),
                ('transaction_limit', models.IntegerField(null=True)),
                ('from_time', models.DateTimeField(null=True)),
                ('till_time', models.DateTimeField(null=True)),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('token_address', models.CharField(max_length=50, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'api_bloxy_source',
            },
        ),
        migrations.CreateModel(
            name='CatvHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('wallet_address', models.CharField(max_length=256)),
                ('token_address', models.CharField(max_length=256, null=True)),
                ('source_depth', models.IntegerField(default=0)),
                ('distribution_depth', models.IntegerField(default=0)),
                ('transaction_limit', models.IntegerField()),
                ('from_date', models.CharField(max_length=10)),
                ('to_date', models.CharField(max_length=10)),
                ('token_type', models.CharField(max_length=10)),
                ('logged_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'api_catv_history',
            },
        ),
        migrations.CreateModel(
            name='CatvJobQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('retries_remaining', models.IntegerField(default=3)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'api_catv_job_queue',
            },
        ),
        migrations.CreateModel(
            name='CatvPathHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('address_from', models.CharField(max_length=256)),
                ('address_to', models.CharField(max_length=256)),
                ('token_address', models.CharField(max_length=256, null=True)),
                ('depth', models.IntegerField(default=0)),
                ('min_tx_amount', models.FloatField(default=0.0)),
                ('from_date', models.CharField(max_length=10)),
                ('to_date', models.CharField(max_length=10)),
                ('limit_address_tx_count', models.IntegerField(default=0)),
                ('token_type', models.CharField(max_length=10)),
                ('logged_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'api_catv_path_history',
            },
        ),
        migrations.CreateModel(
            name='CatvRequestStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('status', enumfields.fields.EnumField(default='progress', enum=api.models.CatvTaskStatusType, max_length=10)),
                ('user_id', models.IntegerField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('labels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('token_type', enumfields.fields.EnumField(default='ETH', enum=api.models.CatvTokens, max_length=10)),
            ],
            options={
                'db_table': 'api_catv_request_status',
            },
        ),
        migrations.CreateModel(
            name='CatvResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_file_id', models.IntegerField(null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='api.CatvRequestStatus')),
            ],
            options={
                'db_table': 'api_catv_result',
            },
        ),
        migrations.AddIndex(
            model_name='catvrequeststatus',
            index=models.Index(fields=['status'], name='api_catv_re_status_95c57b_idx'),
        ),
        migrations.AddIndex(
            model_name='catvrequeststatus',
            index=models.Index(fields=['user_id'], name='api_catv_re_user_id_f08bd3_idx'),
        ),
        migrations.AddIndex(
            model_name='catvrequeststatus',
            index=models.Index(fields=['uid'], name='api_catv_re_uid_f3ac07_idx'),
        ),
        migrations.AddIndex(
            model_name='catvpathhistory',
            index=models.Index(fields=['user_id', 'token_type'], name='api_catv_pa_user_id_214af0_idx'),
        ),
        migrations.AddIndex(
            model_name='catvjobqueue',
            index=models.Index(fields=['retries_remaining'], name='api_catv_jo_retries_1eb8c9_idx'),
        ),
        migrations.AddIndex(
            model_name='catvjobqueue',
            index=models.Index(fields=['created'], name='api_catv_jo_created_009184_idx'),
        ),
        migrations.AddIndex(
            model_name='catvhistory',
            index=models.Index(fields=['user_id'], name='api_catv_hi_user_id_43b154_idx'),
        ),
        migrations.AddIndex(
            model_name='bloxysource',
            index=models.Index(fields=['address', 'depth_limit', 'from_time', 'till_time'], name='api_bloxy_s_address_d19658_idx'),
        ),
        migrations.AddIndex(
            model_name='bloxydistribution',
            index=models.Index(fields=['address', 'depth_limit', 'from_time', 'till_time'], name='api_bloxy_d_address_588ff4_idx'),
        ),
        migrations.AddIndex(
            model_name='catvresult',
            index=models.Index(fields=['request'], name='api_catv_re_request_7d3733_idx'),
        ),
    ]
