# Generated by Django 2.0.6 on 2018-11-29 06:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20181124_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('body', models.TextField(default='', max_length=1024)),
                ('deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Case')),
                ('ico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ICO')),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Indicator')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['writer'], name='api_comment_writer__3e6a7f_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['case'], name='api_comment_case_id_c771e5_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['indicator'], name='api_comment_indicat_631702_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['ico'], name='api_comment_ico_id_dce763_idx'),
        ),
    ]
