# Generated by Django 2.0.6 on 2018-12-06 07:14

import api.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import enumfields.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20181129_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('target', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('read', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', enumfields.fields.EnumField(enum=api.models.NotificationType, max_length=64)),
                ('initiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiator', to='api.User')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='api.User')),
            ],
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user'], name='api_notific_user_id_145217_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created'], name='api_notific_created_bbc9d2_idx'),
        ),
    ]
