# Generated by Django 2.0.6 on 2018-12-19 07:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20181206_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='environment',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='indicator',
            name='vector',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='security_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, null=True, size=None),
        ),
    ]
