# Generated by Django 2.0.6 on 2018-12-21 04:46

import api.models
import django.contrib.postgres.fields
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20181219_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='environment',
            field=django.contrib.postgres.fields.ArrayField(base_field=enumfields.fields.EnumField(enum=api.models.IndicatorEnvironment, max_length=10), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='vector',
            field=django.contrib.postgres.fields.ArrayField(base_field=enumfields.fields.EnumField(enum=api.models.IndicatorVector, max_length=10), blank=True, null=True, size=None),
        ),
    ]
