# Generated by Django 2.0.6 on 2018-12-27 08:02

import api.models
import django.contrib.postgres.fields
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20181221_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='environment',
            field=django.contrib.postgres.fields.ArrayField(base_field=enumfields.fields.EnumField(enum=api.models.IndicatorEnvironment, max_length=32), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='vector',
            field=django.contrib.postgres.fields.ArrayField(base_field=enumfields.fields.EnumField(enum=api.models.IndicatorVector, max_length=32), blank=True, null=True, size=None),
        ),
    ]
