# Generated by Django 2.0.6 on 2019-01-07 08:57

import api.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20181227_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='pattern_type',
            field=enumfields.fields.EnumField(enum=api.models.IndicatorPatternType, max_length=32),
        ),
    ]
