# Generated by Django 2.0.6 on 2019-01-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20190107_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='annotation',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
