# Generated by Django 2.0.6 on 2019-01-13 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_indicator_annotation'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attachedfile',
            name='api_file_case_id_4eba88_idx',
        ),
        migrations.AddField(
            model_name='attachedfile',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicator', to='api.Indicator'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='indicator_reporter', to='api.User'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='reporter_info',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name='attachedfile',
            index=models.Index(fields=['case', 'indicator'], name='api_file_case_id_997e04_idx'),
        ),
    ]
