# Generated by Django 2.0.6 on 2019-01-13 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20190113_0439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='reporter',
        ),
    ]
