# Generated by Django 2.0.6 on 2019-01-25 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_remove_indicator_reporter'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'api_m2m_case_indicator',
            },
        ),
        migrations.RemoveIndex(
            model_name='indicator',
            name='api_indicat_case_id_10ba1a_idx',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='case',
        ),
        migrations.AddField(
            model_name='caseindicator',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Case'),
        ),
        migrations.AddField(
            model_name='caseindicator',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Indicator'),
        ),
    ]
