# Generated by Django 2.0.6 on 2019-01-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20190125_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='indicators',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='cases',
        ),
    ]
