# Generated by Django 2.0.6 on 2019-01-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20190125_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='indicators',
            field=models.ManyToManyField(through='api.CaseIndicator', to='api.Indicator'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='cases',
            field=models.ManyToManyField(through='api.CaseIndicator', to='api.Case'),
        ),
    ]
