# Generated by Django 2.0.6 on 2019-02-26 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_annotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Annotation')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Indicator')),
            ],
            options={
                'db_table': 'api_m2m_indicator_annotation',
            },
        ),
        migrations.AddField(
            model_name='indicator',
            name='annotations',
            field=models.ManyToManyField(through='api.IndicatorAnnotation', to='api.Annotation'),
        ),
    ]
