# Generated by Django 2.0.6 on 2019-05-15 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_action_role_rolepermission_userrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleUsageLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_limit', models.IntegerField(default=5, null=True)),
                ('catv_limit', models.IntegerField(default=5, null=True)),
                ('cara_limit', models.IntegerField(default=5, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_role', to='api.Role')),
            ],
            options={
                'db_table': 'api_role_usage_limit',
            },
        ),
    ]
