# Generated by Django 2.0.6 on 2019-05-15 08:56

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_roleusagelimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=api.models.get_default_role, on_delete=django.db.models.deletion.PROTECT, to='api.Role'),
        ),
    ]
