# Generated by Django 2.0.6 on 2019-05-30 10:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloxyDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('depth_limit', models.IntegerField(null=True)),
                ('transaction_limit', models.IntegerField(null=True)),
                ('from_time', models.DateTimeField(null=True)),
                ('till_time', models.DateTimeField(null=True)),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('token_address', models.CharField(max_length=50, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'api_bloxy_distribution',
            },
        ),
        migrations.CreateModel(
            name='BloxySource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('depth_limit', models.IntegerField(null=True)),
                ('transaction_limit', models.IntegerField(null=True)),
                ('from_time', models.DateTimeField(null=True)),
                ('till_time', models.DateTimeField(null=True)),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('token_address', models.CharField(max_length=50, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'api_bloxy_source',
            },
        ),
        migrations.AddIndex(
            model_name='bloxysource',
            index=models.Index(fields=['address', 'depth_limit', 'from_time', 'till_time'], name='api_bloxy_s_address_d19658_idx'),
        ),
        migrations.AddIndex(
            model_name='bloxydistribution',
            index=models.Index(fields=['address', 'depth_limit', 'from_time', 'till_time'], name='api_bloxy_d_address_588ff4_idx'),
        ),
    ]
