# Generated by Django 2.0.6 on 2019-06-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20190530_1803'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['uid'], name='api_case_uid_8679b0_idx'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['uid'], name='api_indicat_uid_85aac5_idx'),
        ),
    ]
