# Generated by Django 2.0.6 on 2019-06-20 04:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20190612_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatvHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=50)),
                ('token_address', models.CharField(max_length=50, null=True)),
                ('source_depth', models.IntegerField(default=0)),
                ('distribution_depth', models.IntegerField(default=0)),
                ('transaction_limit', models.IntegerField()),
                ('from_date', models.CharField(max_length=10)),
                ('to_date', models.CharField(max_length=10)),
                ('logged_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
            options={
                'db_table': 'api_catv_history',
            },
        ),
    ]
