# Generated by Django 2.0.6 on 2019-06-24 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_catvhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_calls_left', models.IntegerField(default=0)),
                ('catv_calls_left', models.IntegerField(default=0)),
                ('cara_calls_left', models.IntegerField(default=0)),
                ('last_renewal_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='catvhistory',
            index=models.Index(fields=['user'], name='api_catv_hi_user_id_43b154_idx'),
        ),
        migrations.AddField(
            model_name='usage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AddIndex(
            model_name='usage',
            index=models.Index(fields=['user'], name='api_usage_user_id_d9fdaa_idx'),
        ),
        migrations.RunSQL(
            ["INSERT INTO api_usage(user_id,api_calls_left,catv_calls_left,cara_calls_left,last_renewal_at)"
             "select au.id, ul.api_limit,ul.catv_limit,ul.cara_limit,now() from api_user au "
             "inner join api_role ar on au.role_id = ar.id inner join api_role_usage_limit ul "
             "on ar.id = ul.role_id order by au.id;"],
            ["SELECT 0;"],
        ),
    ]
