# Generated by Django 2.0.6 on 2019-06-28 10:02

import api.models
from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20190624_1704'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name='case',
            index=api.models.CustomGinIndex(fields=['title'], name='api_case_title_79f4c8_gin'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=api.models.CustomGinIndex(fields=['pattern'], name='api_indicat_pattern_0bdb98_gin'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=api.models.CustomGinIndex(fields=['pattern_subtype'], name='api_indicat_pattern_d6c7f1_gin'),
        ),
    ]
