# Generated by Django 2.0.6 on 2019-07-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20190628_1802'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['annotation'], name='api_indicat_annotat_796b92_idx'),
        ),
    ]
