# Generated by Django 2.0.6 on 2019-07-17 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_auto_20190710_1608'),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE OR REPLACE FUNCTION public.array_to_text(text[]) RETURNS text LANGUAGE 'sql' IMMUTABLE "
                "AS $BODY$ select $1::text $BODY$;",
            reverse_sql="DROP FUNCTION IF EXISTS public.array_to_text(text[]);"
        ),
        migrations.RunSQL(
            sql="CREATE INDEX text_securitytags_indicator_gin ON public.api_indicator "
                "USING gin(array_to_text(security_tags) gin_trgm_ops);",
            reverse_sql="DROP INDEX IF EXISTS text_securitytags_indicator_gin;"
        ),
    ]
