# Generated by Django 2.0.6 on 2019-07-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_auto_20190717_1713'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['pattern'], name='api_indicat_pattern_aac1d2_idx'),
        ),
    ]
