# Generated by Django 2.0.6 on 2019-09-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_auto_20190719_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_token', models.BigIntegerField(blank=True, null=True)),
                ('token_abi', models.CharField(blank=True, max_length=5196, null=True)),
                ('token_address', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.BigIntegerField(default=0),
        ),
    ]
