# Generated by Django 2.0.6 on 2019-09-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20190909_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='display_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.RunSQL("UPDATE api_role as ar set display_name=d.display_name "
                          "from (values (1, 'Community User'), (2, 'Paid User'), (3, 'Organization'), (4, 'Sentinel'),"
                          "(5, 'Administrator'), (6, 'Organization (Trial)')) as d(id, display_name) where ar.id=d.id"),
    ]
