# Generated by Django 2.0.6 on 2019-09-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_role_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICFHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=40)),
                ('request_endpoint', models.CharField(max_length=100)),
                ('request_type', models.CharField(max_length=10)),
                ('request_data', models.TextField(null=True)),
                ('logged_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_icf_history',
            },
        ),
        migrations.AddIndex(
            model_name='icfhistory',
            index=models.Index(fields=['api_key'], name='api_icf_his_api_key_18af31_idx'),
        ),
    ]
