# Generated by Django 2.0.6 on 2019-09-20 06:27

from django.db import migrations


def create_api_action(apps, schema_editor):
    Action = apps.get_model('api', 'Action')
    Action.objects.bulk_create(
        [Action(resourceid=5, resource='CATV', action='Export data', codename='export_data'),
         Action(resourceid=5, resource='CATV', action='Export image', codename='export_image'),
         Action(resourceid=6, resource='CARA', action='Export report', codename='export_report')]
    )


def reverse_create_api_action(apps, schema_editor):
    Action = apps.get_model('api', 'Action')
    Action.objects.filter(resourceid__in=[5, 6], codename__in=['export_data', 'export_image', 'export_report']).delete()


def create_api_rolepermissions(apps, schema_editor):
    Action = apps.get_model('api', 'Action')
    Role = apps.get_model('api', 'Role')
    RolePermission = apps.get_model('api', 'RolePermission')
    selected_actions = Action.objects.filter(resourceid__in=[5, 6])
    selected_roles = Role.objects.all()
    for role in selected_roles:
        allowed = False if role.role_name == 'communityuser' else True
        for action in selected_actions:
            RolePermission.objects.create(role=role, action=action, allowed=allowed)


def reverse_create_api_rolepermissions(apps, schema_editor):
    print('Nothing to delete here as the action is a foreign key and deleting it should have a cascade effect on '
          'api_role_permission table')


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ('api', '0061_auto_20190918_1218'),
    ]

    operations = [
        migrations.RunPython(create_api_action, reverse_code=reverse_create_api_action, atomic=True),
        migrations.RunPython(create_api_rolepermissions, reverse_code=reverse_create_api_rolepermissions, atomic=True),
    ]
