# Generated by Django 2.0.6 on 2019-10-07 06:45

import api.models
import api.storages.s3
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import uuid


def update_role_usage_limit(apps, schema_editor):
    Role = apps.get_model('api', 'Role')
    RoleUsageLimit = apps.get_model('api', 'RoleUsageLimit')
    org_role = Role.objects.get(role_name='organization')
    org_trial_role = Role.objects.get(role_name='organization-trial')
    RoleUsageLimit.objects.filter(role=org_role).update(org_invite_limit=20)
    RoleUsageLimit.objects.filter(role=org_trial_role).update(org_invite_limit=10)


def reverse_update_role_usage_limit(apps, schema_editor):
    print("Nothing to do here as the column org_invite_limit will be removed by reversing the migration")


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('api', '0062_auto_20190920_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, storage=api.storages.s3.StaticS3Storage(key='user_img/', region='ap-northeast-2', resize=True), upload_to=api.models.image_upload_path)),
                ('invites_left', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', enumfields.fields.EnumField(enum=api.models.OrganizationUserStatus, max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='roleusagelimit',
            name='org_invite_limit',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AddField(
            model_name='organization',
            name='administrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_admin', to='api.User'),
        ),
        migrations.AddField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(through='api.OrganizationUser', to='api.User'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['administrator'], name='api_organiz_adminis_06cf5f_idx'),
        ),
        migrations.RunPython(update_role_usage_limit, reverse_code=reverse_update_role_usage_limit, atomic=True)
    ]
