# Generated by Django 2.0.6 on 2019-10-17 10:55

import api.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_auto_20191007_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationInvites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('invite_hash', models.CharField(max_length=40)),
                ('inviter_key', models.CharField(max_length=100)),
                ('sent', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', enumfields.fields.EnumField(enum=api.models.OrganizationInviteStatus, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='organization',
            name='invites_left',
        ),
        migrations.AddField(
            model_name='organization',
            name='domains',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=2),
        ),
        migrations.AddField(
            model_name='organizationinvites',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Organization'),
        ),
        migrations.AddField(
            model_name='organizationinvites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AddIndex(
            model_name='organizationinvites',
            index=models.Index(fields=['organization'], name='api_organiz_organiz_86d1f0_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationinvites',
            index=models.Index(fields=['user'], name='api_organiz_user_id_855594_idx'),
        ),
    ]
