# Generated by Django 2.0.6 on 2019-10-22 11:12

from django.db import migrations, models


def create_api_action(apps, schema_editor):
    Action = apps.get_model('api', 'Action')
    Action.objects.create(resourceid=1, resource='Case', action='View organization cases', codename='view_org_cases')


def reverse_create_api_action(apps, schema_editor):
    Action = apps.get_model('api', 'Action')
    Action.objects.filter(resourceid=1, codename='view_org_cases').delete()


def create_role_permissions(apps, schema_editor):
    Action = apps.get_model('api', 'Action')
    RolePermission = apps.get_model('api', 'RolePermission')
    Role = apps.get_model('api', 'Role')
    view_org_action = Action.objects.get(resourceid=1, codename='view_org_cases')
    roles = Role.objects.all()
    for role in roles:
        if role.role_name in ['organization', 'organization-trial']:
            RolePermission.objects.create(allowed=True, action=view_org_action, role=role)
        else:
            RolePermission.objects.create(allowed=False, action=view_org_action, role=role)


def reverse_create_role_permissions(apps, schema_editor):
    Action = apps.get_model('api', 'Action')
    RolePermission = apps.get_model('api', 'RolePermission')
    view_org_action = Action.objects.get(resourceid=1, codename='view_org_cases')
    RolePermission.objects.filter(action=view_org_action).delete()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('api', '0064_auto_20191017_1855'),
    ]

    operations = [
        migrations.RunPython(create_api_action, reverse_code=reverse_create_api_action, atomic=True),
        migrations.RunPython(create_role_permissions, reverse_code=reverse_create_role_permissions, atomic=True),
    ]
