# Generated by Django 2.0.6 on 2019-12-06 04:16

from dateutil.relativedelta import relativedelta
from django.db import migrations
from django.utils.timezone import now

from api.models import UserStatus


def create_missing_api_keys(apps, schema_editor):
    User = apps.get_model('api', 'User')
    Key = apps.get_model('api', 'Key')
    nokey_users = User.objects.filter(key__isnull=True, status=UserStatus.APPROVED.value)
    for user in nokey_users:
        Key.objects.create(user=user, expire_datetime=now() + relativedelta(years=+1))


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_auto_20191022_1912'),
    ]

    operations = [
        migrations.RunPython(create_missing_api_keys, lambda apps, schema_editor: print("No op here")),
    ]
