# Generated by Django 2.0.6 on 2019-12-19 09:20

from django.db import migrations

CREATE_INDICATOR_MVIEW_SQL = "DROP MATERIALIZED VIEW IF EXISTS matvw_indicator_search; " \
                             "CREATE MATERIALIZED VIEW matvw_indicator_search AS " \
                             "select x.id, x.uid, x.security_category, array_to_string(x.security_tags, ', ') as security_tags, " \
                             "array_to_string(x.vector, ', ') as vector, array_to_string(x.environment, ', ') as environment, " \
                             "x.pattern_type, x.pattern_subtype, x.pattern, x.detail, x.created, " \
                             "string_agg(x.status, ', ') as cases, x.annotation as annotations from " \
                             "( " \
                             "select ind.id, ind.uid, ind.security_category, ind.security_tags, ind.vector, " \
                             "ind.environment, ind.pattern_type, ind.pattern_subtype, ind.pattern, ind.detail, " \
                             "ind.created, cas.status, ind.annotation " \
                             "from api_indicator ind left outer join api_m2m_case_indicator ci " \
                             "ON ci.indicator_id = ind.id left outer join api_case cas on ci.case_id = cas.id " \
                             ") x " \
                             "group by x.id, x.uid, x.security_category, x.security_tags, x.vector, x.environment," \
                             "x.pattern_type, x.pattern_subtype, x.pattern, x.detail, x.created, x.annotation;"

DROP_INDICATOR_MVIEW_SQL = "DROP MATERIALIZED VIEW IF EXISTS matvw_indicator_search;"


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0066_auto_20191206_1216'),
    ]

    operations = [
        migrations.RunSQL(
            sql=CREATE_INDICATOR_MVIEW_SQL,
            reverse_sql=DROP_INDICATOR_MVIEW_SQL
        ),
    ]
