# Generated by Django 2.0.6 on 2020-01-30 06:43

from django.db import migrations

CREATE_INDICATOR_MVIEW_SQL = "DROP MATERIALIZED VIEW IF EXISTS matvw_indicator_search; " \
                             "CREATE MATERIALIZED VIEW matvw_indicator_search AS " \
                             "SELECT x.*, cas1.uid as latest_case " \
                             "FROM " \
                             "( " \
                             "SELECT ind.id,ind.uid,ind.security_category, " \
                             "array_to_string(ind.security_tags, ', '::text) AS security_tags, " \
                             "array_to_string(ind.vector, ', '::text) AS vector, " \
                             "array_to_string(ind.environment, ', '::text) AS environment, " \
                             "ind.pattern_type,ind.pattern_subtype,ind.pattern,ind.detail,ind.created, " \
                             "string_agg(cas.status::text, ', '::text) AS cases, " \
                             "ind.annotation as annotations,max(ci.case_id) as latest_case_id " \
                             "FROM api_indicator ind " \
                             "LEFT JOIN api_m2m_case_indicator ci ON ci.indicator_id = ind.id " \
                             "LEFT JOIN api_case cas ON ci.case_id = cas.id " \
                             "group by ind.id, ind.uid, ind.security_category, ind.pattern_type, " \
                             "ind.pattern_subtype, ind.pattern, ind.detail, ind.created, ind.annotation " \
                             ") x " \
                             "left join api_case cas1 on x.latest_case_id = cas1.id; "

DROP_INDICATOR_MVIEW_SQL = "DROP MATERIALIZED VIEW IF EXISTS matvw_indicator_search; "


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_auto_20191219_1720'),
    ]

    operations = [
        migrations.RunSQL(
            sql=CREATE_INDICATOR_MVIEW_SQL,
            reverse_sql=DROP_INDICATOR_MVIEW_SQL
        )
    ]
