# Generated by Django 2.0.6 on 2020-01-16 09:50

import api.models
from django.db import migrations
import enumfields.fields


CREATE_CATV_HISTORY_VIEW_SQL = "DROP VIEW IF EXISTS vw_catv_history; " \
                               "CREATE VIEW vw_catv_history WITH (security_barrier=true) AS " \
                               "select x.wallet_address, x.token_address, x.source_depth, x.distribution_depth, " \
                               "x.transaction_limit, x.from_date, x.to_date, x.logged_time, x.user_id, x.token_type, x.row_num from (" \
                               "select wallet_address, token_address, source_depth, distribution_depth, " \
                               "transaction_limit, from_date, to_date, logged_time, user_id, token_type, row_number() OVER (" \
                               "PARTITION BY wallet_address, token_address, source_depth, distribution_depth, " \
                               "transaction_limit, from_date, to_date, user_id, token_type ORDER BY logged_time desc) as row_num " \
                               "from api_catv_history order by logged_time desc) x;"

DROP_CATV_HISTORY_VIEW_SQL = "DROP VIEW IF EXISTS vw_catv_history;"


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_auto_20191219_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='catvhistory',
            name='token_type',
            field=enumfields.fields.EnumField(default='ETH', enum=api.models.CatvTokens, max_length=10),
        ),
        migrations.RunSQL(
            sql=CREATE_CATV_HISTORY_VIEW_SQL,
            reverse_sql=DROP_CATV_HISTORY_VIEW_SQL
        ),
    ]
