# Generated by Django 2.0.6 on 2020-02-24 09:47

import api.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import enumfields.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_auto_20200203_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatvPathHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_from', models.CharField(max_length=100)),
                ('address_to', models.CharField(max_length=100)),
                ('token_address', models.CharField(max_length=100, null=True)),
                ('depth', models.IntegerField(default=0)),
                ('min_tx_amount', models.FloatField(default=0.0)),
                ('from_date', models.CharField(max_length=10)),
                ('to_date', models.CharField(max_length=10)),
                ('limit_address_tx_count', models.IntegerField(default=0)),
                ('token_type', enumfields.fields.EnumField(default='ETH', enum=api.models.CatvTokens, max_length=10)),
                ('logged_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'api_catv_path_history',
            },
        ),
        migrations.AddField(
            model_name='catvpathhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AddIndex(
            model_name='catvpathhistory',
            index=models.Index(fields=['user', 'token_type'], name='api_catv_pa_user_id_214af0_idx'),
        ),
    ]
