# Generated by Django 2.0.6 on 2020-02-24 09:49

from django.db import migrations

CREATE_CATV_PATH_VIEW_SQL = "DROP VIEW IF EXISTS vw_catv_path_history; " \
                            "CREATE VIEW vw_catv_path_history WITH (security_barrier=true) AS " \
                            "select x.address_from, x.address_to, x.token_address, x.depth, x.from_date, " \
                            "x.to_date, x.logged_time, x.user_id, x.token_type, x.row_num from (" \
                            "select address_from, address_to, token_address, depth, from_date, " \
                            "to_date, logged_time, user_id, token_type, row_number() OVER (" \
                            "PARTITION BY address_from, address_to, token_address, depth, from_date, " \
                            "to_date, user_id, token_type ORDER BY logged_time desc) as row_num " \
                            "from api_catv_path_history order by logged_time desc) x;"

DROP_CATV_PATH_VIEW_SQL = "DROP VIEW IF EXISTS vw_catv_path_history;"


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0070_auto_20200224_1747'),
    ]

    operations = [
        migrations.RunSQL(
            sql=CREATE_CATV_PATH_VIEW_SQL,
            reverse_sql=DROP_CATV_PATH_VIEW_SQL
        ),
    ]
