# Generated by Django 2.0.6 on 2020-04-13 10:08

import api.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone
import enumfields.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_auto_20200224_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerErrorLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('message', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('error_trace', models.TextField()),
                ('logged_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'api_consumer_error_logs',
            },
        ),
        migrations.CreateModel(
            name='ExchangeToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_amount', models.IntegerField(blank=True, null=True)),
                ('status', enumfields.fields.EnumField(default='PENDING_APPROVAL', enum=api.models.ExchangeStatus, max_length=10)),
                ('req_time', models.CharField(blank=True, max_length=1024, null=True)),
                ('app_time', models.CharField(blank=True, max_length=1024, null=True)),
                ('upp', models.IntegerField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'api_exchange_token',
            },
        ),
        migrations.AddField(
            model_name='rewardsetting',
            name='sentinel_point_reward',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewardsetting',
            name='sp_required',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewardsetting',
            name='upp_reward',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='consumererrorlogs',
            index=models.Index(fields=['topic'], name='api_consume_topic_ed9e7c_idx'),
        ),
    ]
