# Generated by Django 2.0.6 on 2020-04-17 11:44

from django.db import migrations

COMPOSITE_INDEX_SQL = "CREATE INDEX CONCURRENTLY api_indicator_subtype_updated " \
                      "ON public.api_indicator USING btree (updated DESC) " \
                      "TABLESPACE pg_default " \
                      "WHERE pattern_subtype='ETH';"

DROP_COMPOSITE_INDEX_SQL = "DROP INDEX CONCURRENTLY IF EXISTS " \
                           "api_indicator_subtype_updated;"


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('api', '0072_auto_20200413_1808'),
    ]

    operations = [
        migrations.RunSQL(
            sql=COMPOSITE_INDEX_SQL,
            reverse_sql=DROP_COMPOSITE_INDEX_SQL
        ),
    ]
