# Generated by Django 2.0.6 on 2020-05-18 08:29

import api.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import enumfields.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_auto_20200417_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorMView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('security_category', models.CharField(max_length=10)),
                ('security_tags', models.TextField(blank=True, null=True)),
                ('vector', models.TextField(blank=True, null=True)),
                ('environment', models.TextField(blank=True, null=True)),
                ('pattern_type', models.CharField(max_length=32)),
                ('pattern_subtype', models.CharField(blank=True, max_length=10, null=True)),
                ('pattern', models.CharField(max_length=256)),
                ('detail', models.TextField(blank=True, default='', max_length=4096, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('cases', models.TextField(blank=True, null=True)),
                ('annotations', models.CharField(blank=True, max_length=256, null=True)),
                ('latest_case', models.UUIDField(editable=False, null=True)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'matvw_indicator_search',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExchangeToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_amount', models.IntegerField(blank=True, null=True)),
                ('status', enumfields.fields.EnumField(default='PENDING_APPROVAL', enum=api.models.ExchangeStatus, max_length=10)),
                ('req_time', models.CharField(blank=True, max_length=1024, null=True)),
                ('app_time', models.CharField(blank=True, max_length=1024, null=True)),
                ('upp', models.IntegerField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'api_exchange_token',
            },
        ),
        migrations.AddField(
            model_name='rewardsetting',
            name='sentinel_point_reward',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewardsetting',
            name='sp_required',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewardsetting',
            name='upp_reward',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.BigIntegerField(default=0),
        ),
    ]
