# Generated by Django 2.0.6 on 2020-05-18 08:40

import api.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import enumfields.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_auto_20200518_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatvRequestStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('status', enumfields.fields.EnumField(default='progress', enum=api.models.CatvTaskStatusType, max_length=10)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_catv_request_status',
            },
        ),
        migrations.CreateModel(
            name='IndicatorExtraAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=256)),
                ('annotation', models.CharField(blank=True, max_length=256, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_indicator_extra_annotation',
            },
        ),
        migrations.AddField(
            model_name='case',
            name='rich_text_detail',
            field=models.CharField(default='', max_length=4096),
        ),
        migrations.AddIndex(
            model_name='indicatorextraannotation',
            index=api.models.CustomGinIndex(fields=['pattern'], name='api_indicat_pattern_d32062_gin'),
        ),
        migrations.AddIndex(
            model_name='indicatorextraannotation',
            index=models.Index(fields=['annotation'], name='api_indicat_annotat_41f1a1_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatorextraannotation',
            index=models.Index(fields=['pattern'], name='api_indicat_pattern_66a3e3_idx'),
        ),
        migrations.AddField(
            model_name='catvrequeststatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AddIndex(
            model_name='catvrequeststatus',
            index=models.Index(fields=['status'], name='api_catv_re_status_95c57b_idx'),
        ),
        migrations.AddIndex(
            model_name='catvrequeststatus',
            index=models.Index(fields=['user'], name='api_catv_re_user_id_f08bd3_idx'),
        ),
    ]
