# Generated by Django 2.0.6 on 2020-05-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_auto_20200518_1640'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='catvrequeststatus',
            index=models.Index(fields=['uid'], name='api_catv_re_uid_f3ac07_idx'),
        ),
    ]
