# Generated by Django 2.0.6 on 2020-05-30 17:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_auto_20200528_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatvResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'db_table': 'api_catv_result',
            },
        ),
        migrations.RemoveField(
            model_name='catvrequeststatus',
            name='result',
        ),
        migrations.AddField(
            model_name='catvresult',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='api.CatvRequestStatus'),
        ),
        migrations.AddIndex(
            model_name='catvresult',
            index=models.Index(fields=['request'], name='api_catv_re_request_7d3733_idx'),
        ),
    ]
