# Generated by Django 2.0.6 on 2020-06-01 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_auto_20200531_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catvresult',
            name='result',
        ),
        migrations.AddField(
            model_name='catvresult',
            name='result_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_file', to='api.AttachedFile'),
        ),
    ]
