# Generated by Django 2.0.6 on 2020-06-04 08:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_auto_20200601_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatvJobQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('retries_remaining', models.IntegerField(default=3)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'api_catv_job_queue',
            },
        ),
        migrations.AddIndex(
            model_name='catvjobqueue',
            index=models.Index(fields=['retries_remaining'], name='api_catv_jo_retries_1eb8c9_idx'),
        ),
        migrations.AddIndex(
            model_name='catvjobqueue',
            index=models.Index(fields=['created'], name='api_catv_jo_created_009184_idx'),
        ),
    ]
