# Generated by Django 2.0.6 on 2020-07-16 07:52

import api.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import enumfields.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_auto_20200604_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseMView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(default='', max_length=128)),
                ('detail', models.TextField(default='', max_length=4096)),
                ('rich_text_detail', models.CharField(default='', max_length=4096)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=32)),
                ('reporter_info', models.CharField(blank=True, max_length=128, null=True)),
                ('reporter_id', models.IntegerField(null=True)),
                ('owner_id', models.IntegerField(null=True)),
                ('verifier_id', models.IntegerField(null=True)),
                ('security_category', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32, null=True), null=True, size=None)),
                ('pattern_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32, null=True), null=True, size=None)),
                ('pattern_subtype', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32, null=True), null=True, size=None)),
            ],
            options={
                'db_table': 'matvw_case_search',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserUpgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asked_tokens', models.FloatField(null=True)),
                ('status', enumfields.fields.EnumField(enum=api.models.UpgradeVerifyStatus, max_length=10, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_user_upgrade',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='last_logged_out',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userupgrade',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_user', to='api.User'),
        ),
        migrations.AddIndex(
            model_name='userupgrade',
            index=models.Index(fields=['user'], name='api_user_up_user_id_35a3f8_idx'),
        ),
        migrations.AddIndex(
            model_name='userupgrade',
            index=models.Index(fields=['created'], name='api_user_up_created_e33a7e_idx'),
        ),
    ]
