# Generated by Django 2.0.6 on 2020-07-16 10:11

from django.db import migrations

def create_new_role(apps, schema_editor):
    Role = apps.get_model('api', 'Role')
    Role.objects.create(role_name='communityuser-verified', display_name='Community User (Verified)')

def delete_new_role(apps, schema_editor):
    Role = apps.get_model('api', 'Role')
    Role.objects.filter(role_name='communityuser-verified').delete()

def create_new_role_usage(apps, schema_editor):
    Role = apps.get_model('api', 'Role')
    RoleUsageLimit = apps.get_model('api', 'RoleUsageLimit')
    upgraded_role = Role.objects.get(role_name='communityuser-verified')
    paid_role = Role.objects.get(role_name='paiduser')
    paid_role_usage = RoleUsageLimit.objects.get(role=paid_role)
    RoleUsageLimit.objects.create(
        role=upgraded_role, catv_limit=paid_role_usage.catv_limit,
        cara_limit=paid_role_usage.cara_limit, api_limit=paid_role_usage.api_limit,
        org_invite_limit=paid_role_usage.org_invite_limit
    )
    
def delete_new_role_usage(apps, schema_editor):
    Role = apps.get_model('api', 'Role')
    RoleUsageLimit = apps.get_model('api', 'RoleUsageLimit')
    upgraded_role = Role.objects.get(role_name='communityuser-verified')
    RoleUsageLimit.objects.filter(role=upgraded_role).delete()

def copy_permissions_new_role(apps, schema_editor):
    Role = apps.get_model('api', 'Role')
    RolePermission = apps.get_model('api', 'RolePermission')
    upgraded_role = Role.objects.get(role_name='communityuser-verified')
    paid_role = Role.objects.get(role_name='paiduser')
    paid_role_permissions = RolePermission.objects.filter(role=paid_role)
    for paid_role_permission in paid_role_permissions:
        RolePermission.objects.create(role=upgraded_role, action=paid_role_permission.action,
                                      allowed=paid_role_permission.allowed)

def delete_permissions_new_role(apps, schema_editor):
    Role = apps.get_model('api', 'Role')
    RolePermission = apps.get_model('api', 'RolePermission')
    upgraded_role = Role.objects.get(role_name='communityuser-verified')
    RolePermission.objects.filter(role=upgraded_role).delete()

def create_new_actions(apps, schema_editor):
    Action = apps.get_model('api', 'Action')
    Action.objects.bulk_create(
        [Action(resourceid=5, resource='CATV', action='Access CATV', codename='access_catv'),
         Action(resourceid=6, resource='CARA', action='Access CARA', codename='access_cara'),
         Action(resourceid=3, resource='API', action='Access API', codename='access_api')]
    )

def delete_new_actions(apps, schema_editor):
    Action = apps.get_model('api', 'Action')
    Action.objects.filter(resourceid__in=[3, 5, 6], codename__in=['access_api', 'access_catv', 'access_cara']).delete()

def create_new_permissions_all(apps, schema_editor):
    Action = apps.get_model('api', 'Action')
    Role = apps.get_model('api', 'Role')
    RolePermission = apps.get_model('api', 'RolePermission')
    selected_actions = Action.objects.filter(resourceid__in=[3, 5, 6], codename__in=['access_api', 'access_catv', 'access_cara'])
    selected_roles = Role.objects.all()
    for role in selected_roles:
        allowed = False if role.role_name == 'communityuser' else True
        for action in selected_actions:
            RolePermission.objects.create(role=role, action=action, allowed=allowed)

def delete_new_permissions_all(apps, schema_editor):
    Action = apps.get_model('api', 'Action')
    RolePermission = apps.get_model('api', 'RolePermission')
    selected_actions = Action.objects.filter(resourceid__in=[3, 5, 6], codename__in=['access_api', 'access_catv', 'access_cara'])
    for action in selected_actions:
        RolePermission.objects.filter(action=action).delete()

class Migration(migrations.Migration):
    
    atomic = False
    dependencies = [
        ('api', '0081_auto_20200716_1552'),
    ]

    operations = [
        migrations.RunPython(create_new_role, reverse_code=delete_new_role, atomic=True),
        migrations.RunPython(create_new_role_usage, reverse_code=delete_new_role_usage, atomic=True),
        migrations.RunPython(copy_permissions_new_role, reverse_code=delete_permissions_new_role, atomic=True),
        migrations.RunPython(create_new_actions, reverse_code=delete_new_actions, atomic=True),
        migrations.RunPython(create_new_permissions_all, reverse_code=delete_new_permissions_all, atomic=True),
    ]
