# Generated by Django 2.0.6 on 2020-07-17 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_auto_20200716_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupgrade',
            name='tx_hash',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
