# Generated by Django 2.0.6 on 2020-08-03 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_auto_20200717_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icf_rate_limit', models.CharField(default='5/s', max_length=32)),
                ('cara_rate_limit', models.CharField(default='5/s', max_length=32)),
                ('cara_submit_rate_limit', models.CharField(default='5/m', max_length=32)),
                ('catv_rate_limit', models.CharField(default='5/s', max_length=32)),
                ('org_access', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_role', to='api.Role')),
            ],
            options={
                'db_table': 'api_role_info',
            },
        ),
    ]
