# Generated by Django 2.0.6 on 2020-09-03 06:48

from django.db import migrations

from api.models import UserRoles

def create_new_action(apps, schema_editor):
    Action = apps.get_model('api', 'Action')
    Action.objects.create(resourceid=7, resource='Organization', action='Create organization', codename='create_org')

def delete_new_action(apps, schema_editor):
    Action = apps.get_model('api', 'Action')
    Action.objects.filter(resourceid=7, codename='create_org').delete()

def create_new_permission_all(apps, schema_editor):
    Action = apps.get_model('api', 'Action')
    Role = apps.get_model('api', 'Role')
    RolePermission = apps.get_model('api', 'RolePermission')
    selected_action = Action.objects.get(resourceid=7, codename='create_org')
    selected_roles = Role.objects.all()
    for role in selected_roles:
        allowed = False
        if role.role_name in [UserRoles.ORG.value, UserRoles.ORG_TRIAL.value, UserRoles.SUPERSENTINEL.value]:
            allowed = True
        RolePermission.objects.create(role=role, action=selected_action, allowed=allowed)

def delete_new_permission_all(apps, schema_editor):
    Action = apps.get_model('api', 'Action')
    RolePermission = apps.get_model('api', 'RolePermission')
    selected_actions = Action.objects.filter(resourceid=7, codename='create_org')
    for action in selected_actions:
        RolePermission.objects.filter(action=action).delete()

def update_permission_orgcases(apps, schema_editor):
    Action = apps.get_model('api', 'Action')
    RolePermission = apps.get_model('api', 'RolePermission')
    Role = apps.get_model('api', 'Role')
    selected_action = Action.objects.get(resourceid=1, codename='view_org_cases')
    selected_role = Role.objects.get(role_name=UserRoles.SUPERSENTINEL.value)
    RolePermission.objects.filter(role=selected_role, action=selected_action).update(allowed=True)

def reset_permission_orgcases(apps, schema_editor):
    Action = apps.get_model('api', 'Action')
    RolePermission = apps.get_model('api', 'RolePermission')
    Role = apps.get_model('api', 'Role')
    selected_action = Action.objects.get(resourceid=1, codename='view_org_cases')
    selected_role = Role.objects.get(role_name=UserRoles.SUPERSENTINEL.value)
    RolePermission.objects.filter(role=selected_role, action=selected_action).update(allowed=False)

class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ('api', '0084_roleinfo'),
    ]

    operations = [
        migrations.RunPython(create_new_action, reverse_code=delete_new_action, atomic=True),
        migrations.RunPython(create_new_permission_all, reverse_code=delete_new_permission_all, atomic=True),
        migrations.RunPython(update_permission_orgcases, reverse_code=reset_permission_orgcases, atomic=True),
    ]
