# Generated by Django 2.0.6 on 2020-09-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_auto_20200903_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleusagelimit',
            name='max_api_keys',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
