# Generated by Django 2.0.6 on 2020-09-29 07:54

from django.db import migrations, models

from api.models import RoleUsageLimit

UPDATE_YEARLY_LIMITS_SQL = "UPDATE api_role_usage_limit " \
                           "set api_limit_y=api_limit*12, cara_limit_y=cara_limit*12, catv_limit_y=catv_limit*12;"


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_roleusagelimit_max_api_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleusagelimit',
            name='api_limit_y',
            field=models.IntegerField(default=5)
        ),
        migrations.AddField(
            model_name='roleusagelimit',
            name='cara_limit_y',
            field=models.IntegerField(default=5)
        ),
        migrations.AddField(
            model_name='roleusagelimit',
            name='catv_limit_y',
            field=models.IntegerField(default=5)
        ),
        migrations.RunSQL(UPDATE_YEARLY_LIMITS_SQL, "SELECT 0;")
    ]
