# Generated by Django 2.0.6 on 2020-09-29 08:35

from django.db import migrations, models

UPDATE_EXISTING_CREDITS_SQL = "UPDATE api_usage credits " \
                              "set api_calls_left=api_limit, catv_calls_left=catv_limit, cara_calls_left=cara_limit, " \
                              "api_calls=0, catv_calls=0, cara_calls=0, api_calls_left_y=api_limit_y-api_limit, " \
                              "catv_calls_left_y=catv_limit_y-catv_limit, cara_calls_left_y=cara_limit_y-cara_limit, " \
                              "last_renewal_at=now(), last_renewal_at_y=now() " \
                              "FROM api_user au, api_role_usage_limit arul " \
                              "WHERE credits.user_id = au.id AND arul.role_id = au.role_id;"


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_auto_20200929_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='api_calls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usage',
            name='api_calls_left_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usage',
            name='cara_calls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usage',
            name='cara_calls_left_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usage',
            name='catv_calls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usage',
            name='catv_calls_left_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usage',
            name='last_renewal_at_y',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunSQL(UPDATE_EXISTING_CREDITS_SQL, "SELECT 0;")
    ]
