# Generated by Django 2.0.6 on 2020-10-17 06:33

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_auto_20201007_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=256, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, max_length=4096, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='indicator',
            name='s_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=list, size=3),
        ),
    ]
