# Generated by Django 2.0.6 on 2020-10-07 11:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_auto_20200929_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaraSearchHistory',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('query_time', models.DateTimeField()),
                ('error_generated', models.IntegerField(blank=True, null=True)),
                ('blockchain', models.CharField(blank=True, max_length=10, null=True)),
                ('labels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
            ],
            options={
                'db_table': 'cara_search_history',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='catvrequeststatus',
            name='labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
    ]
