# Generated by Django 2.0.6 on 2020-10-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_auto_20201017_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catvhistory',
            name='token_address',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='catvhistory',
            name='wallet_address',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='catvpathhistory',
            name='address_from',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='catvpathhistory',
            name='address_to',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='catvpathhistory',
            name='token_address',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
