# Generated by Django 2.0.6 on 2021-01-21 08:54

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_auto_20201124_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSecurityTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=256, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, max_length=4096, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='indicator',
            name='s_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
