# Generated by Django 2.0.6 on 2021-01-26 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_auto_20210121_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='customer_tag',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['customer_tag'], name='api_case_custome_d9a800_idx'),
        ),
    ]
