# Generated by Django 2.0.6 on 2021-04-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_auto_20210126_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleusagelimit',
            name='cams_limit',
            field=models.IntegerField(default=5, null=True),
        ),
        migrations.AddField(
            model_name='roleusagelimit',
            name='cams_limit_y',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='usage',
            name='cams_calls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usage',
            name='cams_calls_left_y',
            field=models.IntegerField(default=0),
        ),
    ]
