# Generated by Django 2.0.6 on 2021-04-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_auto_20210414_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='cams_calls_left',
            field=models.IntegerField(default=0),
        ),
    ]
