# Generated by Django 2.0.6 on 2021-08-13 06:26

import api.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_usage_cams_calls_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='catvrequeststatus',
            name='token_type',
            field=enumfields.fields.EnumField(default='ETH', enum=api.models.CatvTokens, max_length=10),
        ),
    ]
