FROM python:3.6.5-stretch

MAINTAINER uppsala <developer@sentinelprotocol.io>

ARG PM2_CONFIG_FILE=pm2_catvconsumer.json
ARG EXPOSE_GENERAL_API=false
ARG EXPOSE_FILE_API=false
ARG EXPOSE_SEARCH_API=false
ARG EXPOSE_INTERNAL_API=false
ARG EXPOSE_FREESEARCH_ENDPOINT=false
ARG SLACK_URL=https://hooks.slack.com/services/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
ARG ALLOWED_HOSTS=localhost
ARG CORS_ORIGIN_WHITELIST
ARG PORTAL_API_ENV=production
ARG PORTAL_API_VERSION=1.0
ARG CONTAINER_TYPE=portal_consumer

ENV EXPOSE_GENERAL_API=$EXPOSE_GENERAL_API
ENV EXPOSE_FILE_API=$EXPOSE_FILE_API
ENV EXPOSE_SEARCH_API=$EXPOSE_SEARCH_API
ENV EXPOSE_INTERNAL_API=$EXPOSE_INTERNAL_API
ENV EXPOSE_FREESEARCH_ENDPOINT=$EXPOSE_FREESEARCH_ENDPOINT
ENV ALLOWED_HOSTS=$ALLOWED_HOSTS
ENV CORS_ORIGIN_WHITELIST=$CORS_ORIGIN_WHITELIST
ENV PORTAL_API_ENV=$PORTAL_API_ENV
ENV PORTAL_PM2_CONFIG_FILE=$PM2_CONFIG_FILE
ENV PORTAL_API_VERSION=$PORTAL_API_VERSION
ENV CONTAINER_TYPE=$CONTAINER_TYPE

WORKDIR /app

# Install packages
# Install nodejs and pm2
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get update && \
    apt-get install -y nodejs redis-server gettext && \
    npm install pm2@3.5.1 -g

# Install requirements
COPY ./requirements/${PORTAL_API_ENV}.txt ./requirements.txt
COPY ./library ./library
RUN pip install -r ./requirements.txt && \
    pip install uwsgi && \
    pip install -e ./library/indicator-lib/src/py

# Add uppsala user.

RUN groupadd -g 999 uppsala && \
    useradd -r -u 999 -g uppsala uppsala && \
    chown uppsala:uppsala /app && \
    usermod -d /app uppsala
USER uppsala

# Bundle APP files
COPY . .
COPY ./deploy ./deploy

# Make translations available
RUN django-admin compilemessages

# RUN
CMD pm2-runtime start /app/deploy/conf/$PORTAL_PM2_CONFIG_FILE --web
