FROM python:3.6.5-stretch

MAINTAINER uppsala <developer@sentinelprotocol.io>

ARG PM2_CONFIG_FILE=pm2_dev.json
ARG EXPOSE_GENERAL_API=true
ARG EXPOSE_FILE_API=true
ARG SLACK_URL
ARG ALLOWED_HOSTS
ARG CORS_ORIGIN_WHITELIST
ARG PORTAL_API_ENV=development
ARG PORTAL_API_VERSION
ARG CONTAINER_TYPE=portal_api

ENV EXPOSE_GENERAL_API=$EXPOSE_GENERAL_API
ENV EXPOSE_FILE_API=$EXPOSE_FILE_API
ENV ALLOWED_HOSTS=$ALLOWED_HOSTS
ENV CORS_ORIGIN_WHITELIST=$CORS_ORIGIN_WHITELIST
ENV PORTAL_API_ENV=$PORTAL_API_ENV
ENV PORTAL_PM2_CONFIG_FILE=$PM2_CONFIG_FILE
ENV PORTAL_API_VERSION=$PORTAL_API_VERSION
ENV CONTAINER_TYPE=$CONTAINER_TYPE

WORKDIR /app

# Install packages
# Install nodejs and pm2
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get update && \
    apt-get install -y nodejs redis-server && \
    npm install pm2@3.5.1 -g

# Install requirements
COPY ./requirements/${PORTAL_API_ENV}.txt /app/requirements.txt
COPY ./library /app/library
RUN pip install -r /app/requirements.txt && \
    pip install uwsgi && \
    pip install -e /app/library/indicator-lib/src/py

# Bundle APP files
COPY . /app/

# RUN
CMD pm2-runtime start /app/deploy/conf/$PORTAL_PM2_CONFIG_FILE --web
