FROM asia-docker.pkg.dev/uppsala-devops/application-base-image-repository/py:bullseye-3.13.1

LABEL maintainer="uppsala <developer@sentinelprotocol.io>" \
      description="This image is maintained by the Uppsala team for Sentinel Protocol." \
      version="1.0"

ARG PM2_CONFIG_FILE=pm2_dev.json
ARG EXPOSE_GENERAL_API=true
ARG EXPOSE_FILE_API=true
ARG EXPOSE_SEARCH_API=true
ARG EXPOSE_INTERNAL_API=true
ARG EXPOSE_FREESEARCH_ENDPOINT=true
ARG SLACK_URL
ARG ALLOWED_HOSTS
ARG CORS_ORIGIN_WHITELIST
ARG CATVMS_API_ENV=development
ARG PORTAL_API_VERSION
ARG CONTAINER_TYPE=catvms_api

ENV EXPOSE_GENERAL_API=$EXPOSE_GENERAL_API \
    EXPOSE_FILE_API=$EXPOSE_FILE_API \
    EXPOSE_SEARCH_API=$EXPOSE_SEARCH_API \
    EXPOSE_INTERNAL_API=$EXPOSE_INTERNAL_API \
    EXPOSE_FREESEARCH_ENDPOINT=$EXPOSE_FREESEARCH_ENDPOINT \
    ALLOWED_HOSTS=$ALLOWED_HOSTS \
    CORS_ORIGIN_WHITELIST=$CORS_ORIGIN_WHITELIST \
    CATVMS_API_ENV=$CATVMS_API_ENV \
    PORTAL_PM2_CONFIG_FILE=$PM2_CONFIG_FILE \
    PORTAL_API_VERSION=$PORTAL_API_VERSION \
    CONTAINER_TYPE=$CONTAINER_TYPE \
    PATH=$PATH:/root/google-cloud-sdk/bin

WORKDIR /app

RUN apt-get update --fix-missing && \
    apt-get install -y --no-install-recommends \
    apt-utils \
    curl \
    ca-certificates \
    nodejs \
    redis-server \
    gettext \
    fonts-arphic-ukai \
    fonts-arphic-uming \
    fonts-ipafont-mincho \
    fonts-ipafont-gothic \
    fonts-unfonts-core && \
    curl --proto '=https' --tlsv1.2 -sSf https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get update && \
    apt-get install -y nodejs && \
    npm install pm2@5.4.3 -g --ignore-scripts && \
    curl -sSL https://sdk.cloud.google.com | bash && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install requirements
COPY ./requirements/${CATVMS_API_ENV}.txt /app/requirements.txt
COPY ./library /app/library

RUN pip install --upgrade pip setuptools && \
    pip install -r /app/requirements.txt && \
    pip install uwsgi==2.0.28 && \
    pip install -e /app/library/indicator-lib/src/py

# Bundle APP files
COPY . /app/

# Make translations available
RUN django-admin compilemessages

# RUN
CMD pm2-runtime /app/deploy/conf/$PORTAL_PM2_CONFIG_FILE