FROM python:3.11

MAINTAINER uppsala <developer@sentinelprotocol.io>

ARG PM2_CONFIG_FILE=pm2_dev.json
ARG EXPOSE_GENERAL_API=true
ARG EXPOSE_FILE_API=true
ARG EXPOSE_SEARCH_API=true
ARG EXPOSE_INTERNAL_API=true
ARG EXPOSE_FREESEARCH_ENDPOINT=true
ARG SLACK_URL
ARG ALLOWED_HOSTS
ARG CORS_ORIGIN_WHITELIST
ARG CATVMS_API_ENV=development
ARG PORTAL_API_VERSION
ARG CONTAINER_TYPE=catvms_api

ENV EXPOSE_GENERAL_API=$EXPOSE_GENERAL_API
ENV EXPOSE_FILE_API=$EXPOSE_FILE_API
ENV EXPOSE_SEARCH_API=$EXPOSE_SEARCH_API
ENV EXPOSE_INTERNAL_API=$EXPOSE_INTERNAL_API
ENV EXPOSE_FREESEARCH_ENDPOINT=$EXPOSE_FREESEARCH_ENDPOINT
ENV ALLOWED_HOSTS=$ALLOWED_HOSTS
ENV CORS_ORIGIN_WHITELIST=$CORS_ORIGIN_WHITELIST
ENV CATVMS_API_ENV=$CATVMS_API_ENV
ENV PORTAL_PM2_CONFIG_FILE=$PM2_CONFIG_FILE
ENV PORTAL_API_VERSION=$PORTAL_API_VERSION
ENV CONTAINER_TYPE=$CONTAINER_TYPE

WORKDIR /app

# Install packages
# Install nodejs and pm2
RUN curl -sL https://deb.nodesource.com/setup_20.x | bash -
RUN apt-get update && \
    apt-get install -y \
    nodejs \
    redis-server \
    gettext && \
    npm install pm2@latest -g

RUN apt-get install fonts-arphic-ukai fonts-arphic-uming fonts-ipafont-mincho fonts-ipafont-gothic fonts-unfonts-core

# Install requirements
COPY ./requirements/${CATVMS_API_ENV}.txt /app/requirements.txt
COPY ./library /app/library
RUN pip install --upgrade pip setuptools==58.0.0 && \
    pip install -r /app/requirements.txt && \
    pip install uwsgi && \
    pip install -e /app/library/indicator-lib/src/py

# Bundle APP files
COPY . /app/

# Make translations available
RUN django-admin compilemessages

# RUN
CMD pm2-runtime /app/deploy/conf/$PORTAL_PM2_CONFIG_FILE