version: "3"

services:
  webapi:
    build:
      context: ..
      dockerfile: docker/Dockerfile_dev
    volumes:
      - ..:/app
    environment:
      - PORTAL_API_ENV_PATH=/app/path.env
      - API_TOKEN_ENCRYPT_PRIVATE_KEY=/app/key.private
      - ALLOWED_HOSTS=*
      - C_FORCE_ROOT=1
    ports:
      - 8000:8000

