FROM asia-docker.pkg.dev/uppsala-devops/application-base-image-repository/python:3.13.1-bullseye

LABEL maintainer="uppsala <developer@sentinelprotocol.io>" \
      description="This image is maintained by the Uppsala team for Sentinel Protocol." \
      version="1.0"

ARG PM2_CONFIG_FILE=pm2.json
ARG EXPOSE_GENERAL_API=true
ARG EXPOSE_FILE_API=true
ARG EXPOSE_SEARCH_API=true
ARG EXPOSE_INTERNAL_API=true
ARG EXPOSE_FREESEARCH_ENDPOINT=true
ARG SLACK_URL
ARG ALLOWED_HOSTS
ARG CORS_ORIGIN_WHITELIST
ARG CATVMS_API_ENV=development
ARG PORTAL_API_VERSION
ARG CONTAINER_TYPE=catvms_api

ENV EXPOSE_GENERAL_API=$EXPOSE_GENERAL_API
ENV EXPOSE_FILE_API=$EXPOSE_FILE_API
ENV EXPOSE_SEARCH_API=$EXPOSE_SEARCH_API
ENV EXPOSE_INTERNAL_API=$EXPOSE_INTERNAL_API
ENV EXPOSE_FREESEARCH_ENDPOINT=$EXPOSE_FREESEARCH_ENDPOINT
ENV ALLOWED_HOSTS=$ALLOWED_HOSTS
ENV CORS_ORIGIN_WHITELIST=$CORS_ORIGIN_WHITELIST
ENV CATVMS_API_ENV=$CATVMS_API_ENV
ENV PORTAL_PM2_CONFIG_FILE=$PM2_CONFIG_FILE
ENV PORTAL_API_VERSION=$PORTAL_API_VERSION
ENV CONTAINER_TYPE=$CONTAINER_TYPE

WORKDIR /app

# Install packages
# Install nodejs and pm2
RUN apt-get update --fix-missing && \
    apt-get install -y apt-utils curl && \
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
RUN apt-get update && \
    apt-get install -y \
    nodejs \
    redis-server \
    gettext && \
    npm install pm2@5.4.3 -g

RUN apt-get install fonts-arphic-ukai fonts-arphic-uming fonts-ipafont-mincho fonts-ipafont-gothic fonts-unfonts-core
# Install google cloud CLI
RUN curl -sSL https://sdk.cloud.google.com | bash
ENV PATH $PATH:/root/google-cloud-sdk/bin    
# Install requirements
COPY ./requirements/${CATVMS_API_ENV}.txt ./requirements.txt
COPY ./library ./library
RUN pip install --upgrade pip setuptools && \
    pip install -r /app/requirements.txt && \
    pip install uwsgi==2.0.28 && \
    pip install -e /app/library/indicator-lib/src/py

# Bundle APP files
COPY . .
COPY ./deploy ./deploy

# Make translations available
RUN django-admin compilemessages

# Add uppsala user.

RUN groupadd -g 999 uppsala && \
    useradd -r -u 999 -g uppsala uppsala && \
    chown uppsala:uppsala /app && \
    usermod -d /app uppsala
USER uppsala

# Install pm2-slack
RUN pm2 install pm2-slack
RUN pm2 set pm2-slack:slack_url ${SLACK_URL} && \
    pm2 set pm2-slack:log false && \
    pm2 set pm2-slack:error false && \
    pm2 set pm2-slack:kill true && \
    pm2 set pm2-slack:exception false && \
    pm2 set pm2-slack:restart false && \
    pm2 set pm2-slack:delete true && \
    pm2 set pm2-slack:stop true && \
    pm2 set pm2-slack:'restart overlimit' true && \
    pm2 set pm2-slack:buffer_seconds 5

# RUN
CMD pm2-runtime /app/deploy/conf/$PORTAL_PM2_CONFIG_FILE
