version: "3"

services:
  catv_service:
    build:
      context: ..
      dockerfile: docker/Dockerfile_dev
    volumes:
      - ..:/app
    environment:
      - CATV_MS_API_PATH=/app/dev.env
      - API_TOKEN_ENCRYPT_PRIVATE_KEY=/app/key.private
      - ALLOWED_HOSTS=*
      - C_FORCE_ROOT=1
    env_file:
      #Insert your env file here
      - ../dev.env
    ports:
      - 8180:8000
    extra_hosts:
      - zoo1.prd.upp kafkabroker01.prd.upp:10.14.39.235
      - zoo2.prd.upp kafkabroker02.prd.upp:10.14.39.187
      - zoo3.prd.upp kafkabroker03.prd.upp:10.14.40.193
      - zoo1.stg.upp stgkafkabroker01.stg.upp:10.12.39.108
      - zoo2.stg.upp stgkafkabroker02.stg.upp:10.12.39.87
      - zoo3.stg.upp stgkafkabroker03.stg.upp:10.12.40.59
