version: "3"

services:
  catv_service:
    build:
      context: ..
      dockerfile: docker/Dockerfile_dev
    volumes:
      - ..:/app
    environment:
      - ALLOWED_HOSTS=*
      - C_FORCE_ROOT=1
      - GOOGLE_APPLICATION_CREDENTIALS=/app/secret/uppsala-staging-5d1de3f3e220.json
      - GCP_PROJECT_ID=uppsala-staging
      - GCP_SECRET_NAME=upp-stg-api-catv-service
    ports:
      - 8180:8000
