apiVersion: v1
kind: Service
metadata:
  name: {{ include "portal-catv-chart.fullname" . }}-service
  labels:
    {{- include "portal-catv-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- else if eq .Values.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
  selector:
    {{- include "portal-catv-chart.selectorLabels" . | nindent 4 }}
