from django.conf import settings

TRDB_HOST = settings.TRDB_HOST
TRDB_USERNAME = settings.TRDB_USERNAME
TRDB_PASSWORD = settings.TRDB_PASSWORD
TRDB_PORT = settings.TRDB_PORT
TRDB_DBNAME = settings.TRDB_DBNAME
TRDB_SSL_MODE = settings.TRDB_SSL_MODE

LOCAL_HOST = settings.LOCAL_HOST
LOCAL_DBNAME = settings.LOCAL_DBNAME
LOCAL_USERNAME = settings.LOCAL_USERNAME
LOCAL_PASSWORD = settings.LOCAL_PASSWORD
LOCAL_PORT = settings.LOCAL_PORT
LOCAL_SSL_MODE = settings.LOCAL_SSL_MODE

TIME_INTERVAL = settings.TIME_INTERVAL
